### ISSUE TITLE
Abdul: working with code, Week 1

### ISSUE THREAD

**Issue by aame1** [HackYourFutureBelgium/class-9-10#10]
> !:warning:! Replace `your-user-name` with your actual GitHub user name and `repo-name` with the name of your class repo !:warning:!

- [x] :egg: [Group Intro Repo](https://github.com/aame1/sunday-class1)
- [x] :egg: Started my HYF Directory
- [x] :egg: _First Week on GitHub_
- [x] :egg: [My student bio](https://github.com/HackYourFutureBelgium/class-9-10/blob/master/student-bios/aame1.md)
- [x] :egg: [my `hack-my-future` repo](https://github.com/aame1/hack-my-future)
- [x] :egg: my markdown home page: [Live](https://aame1.github.io), [Source](https://github.com/aame1/aame1.github.io)
- [x] :egg: [My _Learnables_ Project Board](https://github.com/users/aame1/projects/1)

**Comment by colevandersWands** [comment]
Just one dead link.  The link to the source code for your portfolio is not working.

Otherwise all good!

**Comment by aame1** [comment]
> Just one dead link. The link to the source code for your portfolio is not working.
> 
> Otherwise all good!

thanks @colevandersWands  🙏 

Link should be up now. 😸

**Comment by colevandersWands** [comment]
Oops, I see that was my mistake in the template issue.  the link should be https://github.com/aame1/aame1.github.io.

You're good to go! (trusting you'll fix this anyway :)

**Comment by colevandersWands** [comment]
@aame1 , i missed a detail the first time around.  Can you rename your student-bio file to match your github user name?  this way we can find it from your profile on the class home page: https://hackyourfuture.be/class-9-10/?student=aame1

**Comment by aame1** [comment]
> @aame1 , i missed a detail the first time around. Can you rename your student-bio file to match your github user name? this way we can find it from your profile on the class home page: https://hackyourfuture.be/class-9-10/?student=aame1

Thnx @colevandersWands. I put the the issue in ready for review. :) :unicorn:

**Comment by colevandersWands** [comment]
Not quite.  Your bio should be here: https://github.com/hackyourfuturebelgium/class-9-10/tree/master/student-bios/aame1.md

The button called "student-bio" in your details page should open to this

**Comment by aame1** [comment]
> Not quite. Your bio should be here: https://github.com/hackyourfuturebelgium/class-9-10/tree/master/student-bios/aame1.md
> 
> The button called "student-bio" in your details page should open to this

Woops! I totally missed the point. Too much lo-fi beats on my ears. :D. Should be OK now. :unicorn: :unicorn:

**Comment by colevandersWands** [comment]
or the beats aren't loud enough.  it all depends on how much coffee
