### ISSUE TITLE
Mari: Working with code, Week 1

### ISSUE THREAD

**Issue by Meowri** [HackYourFutureBelgium/class-9-10#110]
# Wednesday Check-In

__Working with code, Week 1__

## Progress

This week I have learned Markdown, the how and the why to use it.
I have learned barely how to hold my own with Github.
I have learned this week how to reach out for help and how to approach the course looking towards my end goal in every new thing I learn.

## Blocked

I got stuck on embedding my images with links and getting a clear functioning website on both Github and Chrome. I also took some time to understand Markdown and refreshed myself on some basics of webdesign, only to be shut down by the design limitations of markdown, but that is how I learned what it is for.

## Next Steps

I need to keep better time management, I really enjoy studying on extra platforms and understanding everything thoroughly and between my full time job and the mandatory tasks of the course, I end up biting off more than I can chew.
 
## Tip(s) of the week

I am lucky enough to have access to LinkedIn learning and I find it an invaluable source of constant new information, that I share in the group if it is useful.
GOOGLE! and Youtube!
I also approached my uncle who dabbled in Web design and recruited him to get his skills polished and assist me and challenge each other.
Joel is a great friend and coach assisting me after I am really stuck beyond saving. 
I find help in looking at what my classmates have done/ are doing and visit their github's

**Comment by colevandersWands** [comment]
🏎️... 🐌... 🏆 .  Keep asking questions like yesterday and you'll be fine !

**Comment by Meowri** [comment]
I am not sure if I should close myself, but I am ready for week 2

**Comment by colevandersWands** [comment]
@Meowri , yup!  close it when you're ready: https://home.hackyourfuture.be/students/wednesday-check-in
