### ISSUE TITLE
LujiAnna: working with code, Week 1

### ISSUE THREAD

**Issue by LujiAnna** [HackYourFutureBelgium/class-9-10#118]
> !:warning:! Replace `your-user-name` with your actual GitHub user name and `repo-name` with the name of your class repo !:warning:!

- [x] :egg: [Group Intro Repo](https://github.com/LujiAnna/group-intro)
- [x] :egg: Started my HYF Directory
- [x] :egg: _First Week on GitHub_
- [x] :egg: [My student bio](https://github.com/hackyourfuturebelgium/class-9-10/tree/master/student-bios/LujiAnna.md)
- [x] :egg: [my `hack-my-future` repo](https://github.com/LujiAnna/hack-my-future)
- [x] :egg: my markdown home page: [Live](https://LujiAnna.github.io), [Source](https://github.com/LujiAnna/LujiAnna)
- [x] :egg: [My _Learnables_ Project Board](https://github.com/users/LujiAnna/projects/1)

**Comment by LujiAnna** [comment]
I am having trouble with github page. I have the source well placed, but LujiAnna.github.io is not initializing.

**Comment by colevandersWands** [comment]
well done
