### ISSUE TITLE
Eltayeb: working with code, Week 1

### ISSUE THREAD

**Issue by Eltayeb-Elgaali** [HackYourFutureBelgium/class-9-10#12]
- [x] :egg: [Group Intro Repo](https://github.com/Eltayeb-Elgaali/group-intro)
- [x] :egg: Started my HYF Directory
- [x] :egg: _First Week on GitHub_
- [x] :egg: [My student bio](https://github.com/hackyourfuturebelgium/class-9-10/tree/master/student-bios/Eltayeb-Elgaali.md)
- [x] :egg: [my `hack-my-future` repo](https://github.com/Eltayeb-Elgaali/hack-my-future)
- [x] :egg: my markdown home page: [Live](https://Eltayeb-Elgaali.github.io), [Source](https://github.com/Eltayeb-Elgaali/Eltayeb-Elgaali.github.io)
- [x] :egg: [My _Learnables_ Project Board](https://github.com/users/Eltayeb-Elgaali/projects/1)

**Comment by colevandersWands** [comment]
Well done!
