### ISSUE TITLE
HazemBittar: working with code, Week 1

### ISSUE THREAD

**Issue by HazemBittar** [HackYourFutureBelgium/class-9-10#120]
> !:warning:! Replace `your-user-name` with your actual GitHub user name and `repo-name` with the name of your class repo !:warning:!

- [x] :egg: [Group Intro Repo](https://github.com/HazemBittar/group--intro)
- [x] :egg: Started my HYF Directory
- [x] :egg: _First Week on GitHub_
- [x] :egg: [My student bio](https://github.com/HackYourFutureBelgium/class-9-10/blob/master/student-bios/HazemBittar.md)
- [x] :egg: [my `hack-my-future` repo](https://github.com/HazemBittar/hack-my-future)
- [x] :egg: my markdown home page: [Live](https://hazembittar.github.io), [Source](https://github.com/HazemBittar/HazemBittar.github.io)
- [x] :egg: [My _Learnables_ Project Board](https://github.com/users/HazemBittar/projects/1)

**Comment by colevandersWands** [comment]
💯

**Comment by colevandersWands** [comment]
@HazemBittar , I missed this the first time around.  Can you rename your student bio to match your github user name?   This way we can find it from the links in the class home page: https://hackyourfuture.be/class-9-10/?student=Hazembittar

**Comment by HazemBittar** [comment]
Done! Thank you for feedback @colevandersWands

**Comment by colevandersWands** [comment]
@HazemBittar , can you move your card to "READY FOR REVIEW"?

**Comment by colevandersWands** [comment]
:+1:
