### ISSUE TITLE
Eltayeb : Incremental-Development, week 1, Homework

### ISSUE THREAD

**Issue by Eltayeb-Elgaali** [HackYourFutureBelgium/class-9-10#121]
# Week 1

## Incremental-Development

- [assignments](https://github.com/hackyourfuturebelgium/incremental-development/tree/master/week-1)

## Prep Work

- [x] Git
- [x] Agile Development
- [x] Relative vs. Absolute Paths
- [x] Inspecting the DOM
- [x] HTML 5 Semantic Layout

---

## In Class

- [x] Isolate: I have understood the exercises
- [x] Integrate: [live](https://eltayeb-elgaali.github.io/integrate), [source](https://github.com/Eltayeb-Elgaali/integrate)

---

### Suggested Study

- [x] Git & GitHub
- [x] HTML & CSS

### Exercises:

- [x] :egg: [HTML-CSS-Git-exercises - Week 1](https://github.com/Eltayeb-Elgaali/html-css-git-exercises/tree/master/week-1)
- [x] :hatching_chick:   HTML-CSS-Practice-Problems: 
    - Level 1: [repo](https://github.com/Eltayeb-Elgaali/HTML-CSS-Practice-Problems/tree/master/level-1), [live](https://eltayeb-elgaali.github.io/HTML-CSS-Practice-Problems/level-1/index.html)
    - Level 2: [repo](https://github.com/Eltayeb-Elgaali/HTML-CSS-Practice-Problems/tree/master/level-2), [live](https://eltayeb-elgaali.github.io/HTML-CSS-Practice-Problems/level-2/index.html)
     - Level 3: [repo](https://github.com/Eltayeb-Elgaali/HTML-CSS-Practice-Problems/tree/master/level-3), [live](https://eltayeb-elgaali.github.io/HTML-CSS-Practice-Problems/level-3/index.html)

- [ ] :hatched_chick: :   css-exercises [repo](https://github.com/your-user-name/exercise-name), [live](https://your-user-name.github.io/exercise-name/)

### Project

 :egg:  acme-web-design:

- [x] [repo](https://github.com/Eltayeb-Elgaali/acme-web-design)
- [x] [live](https://eltayeb-elgaali.github.io/acme-web-design/)
- [x] [development-strategy](https://github.com/Eltayeb-Elgaali/acme-web-design/tree/master/development-strategy.md)
- [x] One branch per step in my `development-strategy.md`
- [x] A complete README

**Comment by Eltayeb-Elgaali** [comment]
new issue for week-1 in  Incremental-Development module

**Comment by Eltayeb-Elgaali** [comment]
Add link to HTML-CSS-Git-exercises

**Comment by snicoll** [comment]
Good job @Eltayeb-Elgaali. Please review the following:

* There is an [HTML validation error](https://validator.w3.org/nu/?doc=https%3A%2F%2Feltayeb-elgaali.github.io%2Fintegrate%2F) for the integrate project
* Some more [HTML validation errors](https://validator.w3.org/nu/?doc=https%3A%2F%2Feltayeb-elgaali.github.io%2Facme-web-design%2F) for the acme web design project

Your development strategy looks good, great job!

**Comment by Eltayeb-Elgaali** [comment]
Thank you for the remark .
i have just fix the errors and put the issue back in ready for review

**Comment by snicoll** [comment]
Great job @Eltayeb-Elgaali, thanks!
