### ISSUE TITLE
Miroslav: working-with-code, week 1

### ISSUE THREAD

**Issue by miroslavveljanoski** [HackYourFutureBelgium/class-9-10#122]
# Wednesday Check-In

__working-with-code, week 1__

## Progress

- I have learned how to use and write with Markdown language. 
- I have learned how to make my own project on Github and how to work on it. The assignment to make our own project board and keep organizing our progress was really good.
- How to use the VSC to open and make changes in files, and how to add, commit, push and pull with GitKraken, even though I'm still not comfortable with using GitKraken.
- Some of the tutorials and courses about GitHub helped me to better understand some things. 

## Blocked

- The first days I was struggling with the flow of HYF, I did not know how and what to do, and was really confused. But I think I'm getting better even though still not comfortable :smile: 
- I'm still trying to better understand GitHub and get comfortable using it.
- I'm not sure that I know how to use it the installed plug-ins.

## Next Steps

Watch some tutorials for GitHub, read good posts, and examples in order to better understand it.

## Tip(s) of the week

Don't get nervous when you are stuck. Get some rest, search on Google and ask for help of your classmates and teachers

**Comment by colevandersWands** [comment]
@miroslavveljanoski , your first two "blocked" items are normal after the first week.  There will be enough time to get used to github & the hyf materials.

for vscode plugins, this is certainly something the others are still confused by as well.  why don't you create a [sunday review issue](https://home.hackyourfuture.be/students/asking-for-help#label-sunday-review) and we can go over this tomorrow
