### ISSUE TITLE
Nadia: working with code, Week 1

### ISSUE THREAD

**Issue by ms-np** [HackYourFutureBelgium/class-9-10#125]
> !:warning:! Replace `your-user-name` with your actual GitHub user name and `repo-name` with the name of your class repo !:warning:!

- [x] :egg: [Group Intro Repo](https://github.com/ms-np/class9-10_Group3)
- [x] :egg: Started my HYF Directory
- [x] :egg: _First Week on GitHub_
- [x] :egg: [My student bio](https://github.com/hackyourfuturebelgium/repo-name/tree/master/student-bios/ms-np.md)
- [x] :egg: [my `hack-my-future` repo](https://github.com/ms-np/hack-my-future/)
- [x] :egg: my markdown home page: [Live](https://ms-np.github.io/), [Source](https://github.com/ms-np/ms-np.github.io)
- [x] :egg: [My _Learnables_ Project Board](https://github.com/ms-np/hack-my-future/projects/1)

**Comment by colevandersWands** [comment]
🌞
