### ISSUE TITLE
Gelilaa: working with code, Week 1

### ISSUE THREAD

**Issue by gelilaa** [HackYourFutureBelgium/class-9-10#13]
> !:warning:! Replace `gelilaa` with your actual GitHub user name and `Working-With-Code` with the name of your class repo !:warning:!

- [x] :egg: [Group Intro Repo]( https://github.com/gelilaa/intro)
- [x] :egg: Started my HYF Directory
- [x] :egg: _First Week on GitHub_
- [x] :egg: [My student bio](https://github.com/HackYourFutureBelgium/class-9-10/blob/master/student-bios/gelilaa.md)
- [x] :egg: [my `hack-my-future` repo](https://github.com/gelilaa/hack-my-future)
- [x] :egg: my markdown home page: [Live](https://gelilaa.github.io/test-week-01/), [Source](https://github.com/gelilaa/test-week-01)
- [x] :egg: [My _Learnables_ Project Board](https://github.com/users/gelilaa/projects/1)

**Comment by colevandersWands** [comment]
@gelilaa , just one thing to change!  can you rename your home page repository to https://github.com/gelilaa/gelilaa.github.io?  you'll know you've got it right when this link works: https://gelilaa.github.io

**Comment by colevandersWands** [comment]
🌷
