### ISSUE TITLE
Abdul: incremental-development, week 1

### ISSUE THREAD

**Issue by aame1** [HackYourFutureBelgium/class-9-10#132]
# Week 1

## Incremental Development

- [assignments](https://github.com/hackyourfuturebelgium/incremental-development/tree/master/week-1)

## Prep Work

- [X] Git
- [X] Agile Development
- [X] Relative vs. Absolute Paths
- [X] Inspecting the DOM
- [X] HTML 5 Semantic Layout

---

### Isolate

- [X] `Team Branchies` [live]( https://aame1.github.io/shiny-potato/) [source](https://github.com/aame1/shiny-potato)
- [x] - `Built with branches` [source](https://github.com/aame1/built-with-branches)

---

### Suggested Study
- [X] Git & GitHub
- [X] Git-it : installed finished the challenges and merged to the jlord's main repo.

### Exercises
- [X] :egg: [html-css-git-exercises](https://github.com/aame1/html-css-git-exercises/tree/master/week-1) - Week 1
- [ ] :hatching_chick: [HTML-CSS-Practice-Problems](https://github.com/DevMountain/HTML-CSS-Practice-Problems)
- [ ] :hatched_chick: [css-exercises](https://github.com/dangodev/css-exercises)

### Project
project name: `the-music-lab` 

- [X] [repo](https://github.com/aame1/the-music-lab)
- [X] [live](https://aame1.github.io/the-music-lab/)
- [X] [development-strategy](https://github.com/aame1/the-music-lab/blob/master/development-strategy.md)
- [X] One branch per step in my `development-strategy.md`
- [X] [A complete README]

**Comment by aame1** [comment]
html-css-git-exercises done. will post on slack tomorrow to ask if OK for Pull request.

**Comment by aame1** [comment]
branching exercises done.

**Comment by aame1** [comment]
Hi all, 

I'm trying to find a point in the history of my commits where i'd apparently changed margins in one of my branches. Annoying, because it makes my section element detached from the one above.
The styling aspect is not really the issue, as much as is the fact that I would like to understand if there's a regret button in such circumstances. :smile:.

So, I would like to update the master with one of my latest commits of a particular branch, but without really modifying the branch.  I would like to re-merge the branch onto master.
Merging it and pushing in master doesn't work, because there are no changes on it and the "master" version in the remote repo is already up to date.

Is there anyway to rollback to a working "section-3" (the name of my branch) and pushing it to the "master" branch without really adding / removing anything ?

This is the link to my live right now : https://aame1.github.io/the-music-lab/

**Comment by otagi** [comment]
From what I can see, you merged the `section-3` branch into `master`, then `section-1`, then `header`, then `section-3` again. 

Do you want `master` to "forget" about `section-1` and `header`? In that case, you can revert these merges with `git revert [id of commit to revert]`.

If that's too radical, you can always get a single file from a previous commit with `git checkout [id of commit] [path/to/the/file]`.

But before doing any of that, a better approach would be for you to review all the changes you made between the working version and the latest one, and find exactly which one introduced the bug. You can easily do that by going to [the commits list](https://github.com/aame1/the-music-lab/commits/master) and click on each commit to see the "diff".

Once you find the bug, if the fix is short enough, then just add the correction in a new commit.

**Comment by aame1** [comment]
> From what I can see, you merged the `section-3` branch into `master`, then `section-1`, then `header`, then `section-3` again.
> 
> Do you want `master` to "forget" about `section-1` and `header`? In that case, you can revert these merges with `git revert [id of commit to revert]`.
> 
> If that's too radical, you can always get a single file from a previous commit with `git checkout [id of commit] [path/to/the/file]`.
> 
> But before doing any of that, a better approach would be for you to review all the changes you made between the working version and the latest one, and find exactly which one introduced the bug. You can easily do that by going to [the commits list](https://github.com/aame1/the-music-lab/commits/master) and click on each commit to see the "diff".
> 
> Once you find the bug, if the fix is short enough, then just add the correction in a new commit.
> 
> **Edit:** Also don't forget to use the "inspect" development tool in your browser, to understand exactly what causes the extra margin.

Thanks a lot for the insights @otagi. 

I traced the issue back thanks to the command you provided : `git checkout hash of commit`

 Finally, seems like the issue came from an added <h2> line into section-1 (that's where inspecting came into play) which of course then impacted my padding-bottom. 

I pushed the changes, compared it with the remote repo and now I'm gently waiting for Github Pages to do the rest. 

Another story of a missing <>  :). :facepalm:

**Comment by otagi** [comment]
Good strategy and code structure!

Minor remarks:

- The branches look messy in the network graph at the beginning, but the last ones are much more straightforward. Good progression!
- The HTML and CSS code could use better alignment and less blank lines in some places. Don't forget there are VSCode extensions to automate this.
- The `azimuth.png` image is quite heavy: 1.63MB, which takes 11s to load on my slow internet connection. It's not super important for this exercise, but in a real project it's good practice to reduce the weight of images as much as possible. Just keep that in mind when you will start real projects. 😉

**Comment by aame1** [comment]
> Good strategy and code structure!
> 
> Minor remarks:
> 
> * The branches look messy in the network graph at the beginning, but the last ones are much more straightforward. Good progression!
> * The HTML and CSS code could use better alignment and less blank lines in some places. Don't forget there are VSCode extensions to automate this.
> * The `azimuth.png` image is quite heavy: 1.63MB, which takes 11s to load on my slow internet connection. It's not super important for this exercise, but in a real project it's good practice to reduce the weight of images as much as possible. Just keep that in mind when you will start real projects. wink

Thank you for the feedback @otagi ! 

Will keep this mind asap.
