### ISSUE TITLE
Yana: Incremental Development, Week 1, Homework

### ISSUE THREAD

**Issue by adekimpianna** [HackYourFutureBelgium/class-9-10#135]
# Week 1

## Incremental Development

- [Assignments](https://github.com/HackYourFutureBelgium/incremental-development/blob/master/week-1/README.md)

---

## Prep Work

- [x] GitHub Poet until 1.4 (Pushing, Pulling, Branches)
- [x] Agile Development and User Stories
- [x] Relative vs. Absolute Paths
- [x] Inspecting the DOM
- [x] HTML 5 Semantic Layout

---

### Isolate

- [x] Team Branchies: [Repo](https://github.com/adekimpianna/team-profile-with-branches), [Live](https://adekimpianna.github.io/team-profile-with-branches/)

### Integrate

- [x] Semantic Layout: [Repo](https://github.com/adekimpianna/semantic-layout-html-css-), [Live](https://adekimpianna.github.io/semantic-layout-html-css-/)

---

### Suggested Study

- [x] GitHub
    - [git & github for poets](https://www.youtube.com/watch?v=BCQHnlnPusY&list=PLRqwX-V7Uu6ZF9C0YMKuns9sLDzK6zoiV)
   - [The Net Ninja](https://www.youtube.com/playlist?list=PL4cUxeGkcC9goXbgTDQ0n_4TBzOO0ocPR)
   - [git-it](https://github.com/jlord/git-it-electron/)
   - [learngitbranching](https://learngitbranching.js.org)
- [x] HTML, CSS
   - [How to inspect an element](https://www.lifewire.com/get-inspect-element-tool-for-browser-756549)
   - [Modify the DOM. (does the source change?)](https://zapier.com/blog/inspect-element-tutorial/)
   - [inspecting-the-dom](https://hackyourfuture.be/inspecting-the-dom)
   - FCC, Responsive Web Design: [exercises](https://www.freecodecamp.org/learn), [video](https://www.youtube.com/watch?v=srvUrASNj0s)
   - [mmtuts: HTML & CSS](https://www.youtube.com/watch?v=TKYsuU86-DQ&list=PL0eyrZgxdwhwNC5ppZo_dYGVjerQY3xYU)

### Exercises

- [x] :egg: Exercise 1 [html-css-git-exercises](https://github.com/hackyourfuturebelgium/html-css-git-exercises) - Week 1 [Repo](https://github.com/adekimpianna/html-css-git-exercises/branches)
- [ ] :hatching_chick: [HTML-CSS-Practice-Problems](https://github.com/DevMountain/HTML-CSS-Practice-Problems), [Repo](https://github.com/your-user-name/exercise-name)
- [ ] :hatched_chick: [CSS-exercises](https://github.com/dangodev/css-exercises)

### Project

`:emoji:` ACME WEB DESIGN

- [x] [Repo](https://github.com/adekimpianna/acme-web-design)
- [x] [Live](https://adekimpianna.github.io/acme-web-design/)
- [x] [Development-strategy](https://github.com/adekimpianna/acme-web-design/blob/master/development-strategy.md)
- [x] One branch per step in my `development-strategy.md`
- [x] A complete [README](https://github.com/adekimpianna/acme-web-design/blob/master/README.md)

**Comment by snicoll** [comment]
@Yana well done, I like your development strategy
