### ISSUE TITLE
Kateryna, Incremental Development, Week 1, Homework

### ISSUE THREAD

**Issue by katerynakim** [HackYourFutureBelgium/class-9-10#138]
[assignments](https://github.com/hackyourfuturebelgium/incremental-development/tree/master/week-1)

### Git

- [x]  git & github for poets - no need to go past 1.4
- [x]  The Net Ninja - 8 & 9
- [x]  Understand how to use Atomic Commits

### Agile Development

- [x]  Development Strategy (required) - development-strategy.md files - example: Team Branchies
- [x]  What is this?
- [x] Agile Development by Cartoon
- [x] Splitting User Stories
- [x] The "what" not the "how"

### Relative vs Absolute 

- [x] relative vs. absolute paths
- [x] Inspecting the DOM
- [x] How to inspect an element
- [x] Modify the DOM. (does the source change?)

###  HTML 5 Semantic Layout

- [x] [MDN](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Document_and_website_structure)
- [x] [w3schools 1](https://www.w3schools.com/html/html_layout.asp)
- [x] [w3schools 2](https://www.w3schools.com/html/html5_semantic_elements.asp)

#### Git & Github

- [x] [git & github for poets](https://www.youtube.com/watch?v=BCQHnlnPusY&list=PLRqwX-V7Uu6ZF9C0YMKuns9sLDzK6zoiV)
- [x]  [The Net Ninja](https://www.youtube.com/playlist?list=PL4cUxeGkcC9goXbgTDQ0n_4TBzOO0ocPR)
- [x]  [git-it](https://github.com/jlord/git-it-electron/)
- [x]  [learngitbranching](https://learngitbranching.js.org)

#### HTML & CSS

- [x] [How to inspect an element](https://www.lifewire.com/get-inspect-element-tool-for-browser-756549)
- [x] [Modify the DOM. (does the source change?)](https://zapier.com/blog/inspect-element-tutorial/)
- [x]  [inspecting-the-dom](https://hackyourfuture.be/inspecting-the-dom)
- [x]  FCC, Responsive Web Design: [exercises](https://www.freecodecamp.org/learn), [video](https://www.youtube.com/watch?v=srvUrASNj0s)
- [x]  [mmtuts: HTML & CSS](https://www.youtube.com/watch?v=TKYsuU86-DQ&list=PL0eyrZgxdwhwNC5ppZo_dYGVjerQY3xYU)

### Exercises:
- [x] Isolate 
[live](https://katerynakim.github.io/team-branches-group-/)
[repo](https://github.com/katerynakim/team-branches-group-)
- [x] Integrate 
[live](https://katerynakim.github.io/semantic/)
[repo](https://github.com/katerynakim/semantic)

- [x] :egg: [html-css-git-exercises]
[repo](https://github.com/katerynakim/html-css-git-exercises/tree/master/week-1)

 - Week 1
  - Fork & clone the repository
  - Complete the exercises in `week-1`
  - Push your work regularly to GitHub
- [ ]  :hatching_chick: [HTML-CSS-Practice-Problems](https://github.com/DevMountain/HTML-CSS-Practice-Problems)
- [ ]  :hatched_chick: [css-exercises](https://github.com/dangodev/css-exercises)

#### `acme-web-design`

 - [x] [Code-Along](https://home.hackyourfuture.be/students/weekly-assignments#projects)
[live](https://katerynakim.github.io/acme-webdesign/)
[repo](https://github.com/katerynakim/acme-webdesign)

**Comment by katerynakim** [comment]
Hello Everyone,

Could please anyone advise what should I do in this case. I just started doing html-css-git-exercises - Week 1, followed all the instructions and blocked on **following step : begin working on the exercises
To work on the first exercise, run the following command in the Terminal.
npm install**.
Once the command is performed on the terminal, I get the following message: 
npm : The term 'npm' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify th
at the path is correct and try again.
Attached screenshot for your reference.
![image](https://user-images.githubusercontent.com/63308447/82434154-c210b900-9a92-11ea-8f2d-d60623e4bab5.png)

Thank you in advance 👍

**Comment by IrynaSpyrydonova** [comment]
Hi Kateryna, i think you have first to check if node.js is already installed on your laptop. For that run `node  -v`, it will show the version of node if you have it. if no - follow the steps from this [website](https://nodejs.org/en/) to install it.  Hope it will help.

**Comment by katerynakim** [comment]
> Hi Kateryna, i think you have first to check if node.js is already installed on your laptop. For that run `node -v`, it will show the version of node if you have one. If no - follow the instructions from this [website](https://nodejs.org/en/) to install it. Hope it will help.

Thank you Iryna! You helped a lot :)

**Comment by snicoll** [comment]
@katerynakim great job and your "The Basics of “Good Wine” page is really original, I love it!

I've found a few things you may want to look at:

* There is an [HTML validation warning](https://validator.w3.org/nu/?doc=https%3A%2F%2Fkaterynakim.github.io%2Fsemantic%2F) for your integrate exercise
* There are [a few more HTML validation warnings](https://validator.w3.org/nu/?doc=https%3A%2F%2Fkaterynakim.github.io%2Facme-webdesign%2F) for the acme web design page
* The wireframe of your [development strategy](https://katerynakim.github.io/acme-webdesign/development-strategy) does not show up. You've used `/images` but the directory is named `img`. This is a relative path so it should not start with `/` 
* You should review your development strategy so that each story has a title. Compare with the other development strategy that you've seen so far. They all describe a  feature, an added value to the site.

**Comment by katerynakim** [comment]
Dear  Stephan @snicoll ,

Thank you so much for reviewing my homework.
I have fixed all the proposed changes:

- I have fixed [HTML validation errors](https://validator.w3.org/nu/?doc=https%3A%2F%2Fkaterynakim.github.io%2Fsemantic%2F) for integrate exercise.
- _Acme Web Design_:
1. Fixed HTML error for the [HOME PAGE](https://validator.w3.org/nu/?doc=https%3A%2F%2Fkaterynakim.github.io%2Facme-webdesign%2Findex.html).
2.  Fixed HTML error for the [ABOUT PAGE](https://validator.w3.org/nu/?doc=https%3A%2F%2Fkaterynakim.github.io%2Facme-webdesign%2Fabout.html).
But still I receive warning with <lang> tag, it must be because I have used Lorem ipsum.
Should I have changed it to lang="zxx"?
3. Fixed HTM error for the [SERVICES PAGE](https://validator.w3.org/nu/?doc=https%3A%2F%2Fkaterynakim.github.io%2Facme-webdesign%2Fservices.html).
4. Updated (Development Strategy)[https://katerynakim.github.io/acme-webdesign/development-strategy].
5. Updated the (wireframe)[https://katerynakim.github.io/acme-webdesign/development-strategy].

Please let me know if there is anything else that should be corrected.

Thank you!

**Comment by snicoll** [comment]
@katerynakim thanks for the follow-up, that looks great!

> But still I receive warning with tag, it must be because I have used Lorem ipsum.

This one is fine, you can ignore it.

Your development strategy looks better. Nitpicking on the following:

> Following User story displays a cathy slogan and a copywrite text, which gives short, but undertandable overview about the company. Relative image was added as a background. Newsletter is feature will be used to communicate regularly with your subscriber.

This is too detailed to be a user story title. A title is one sentence with a persona. I know it can be hard sometimes to summarize something with one sentence but that's what you'll have to do when creating issues too.

No need to act on it, I think you're done for that week, thanks!
