### ISSUE TITLE
Harun Altun: Incremental Development, week 1, Homework

### ISSUE THREAD

**Issue by harunaltunhr** [HackYourFutureBelgium/class-9-10#139]
# Week 1

## Incremental Development

- [Assignments](https://github.com/hackyourfuturebelgium/incremental-development/tree/master/week-1)

## Prep Work
- [X] Git
- [X] Agile Development
- [X] Relative vs. Absolute Paths
- [X] Inspecting the DOM
- [X] HTML 5 Semantic Layout

---

### Isolate

- [X] `Team Branchies` [live]( https://harunaltunhr.github.io/team_branchies) [source](https://github.com/harunaltunhr/team_branchies )

### Integrate
- [X] `Semantic layout` [live]( https://harunaltunhr.github.io/built-with-branches/) [source](https://github.com/harunaltunhr/built-with-branches )
---

### Suggested Study
- [X] Git & GitHub
- [X] HTML & CSS
### Exercises
- [X] :egg: [html-css-git-exercises](https://github.com/harunaltunhr/html-css-git-exercises/tree/master/week-1) - Week 1
- [X] :hatching_chick: [HTML-CSS-Practice-Problems](https://github.com/harunaltunhr/HTML-CSS-Practice-Problems)
- [ ] :hatched_chick: [css-exercises](https://github.com/dangodev/css-exercises)

### Project
project name: `acme-web-design` 

- [X] [repo](https://github.com/harunaltunhr/acme-web-design)
- [X] [live](https://harunaltunhr.github.io/acme-web-design/)
- [X] [development-strategy](https://github.com/harunaltunhr/acme-web-design/blob/master/development-strategy.md)
- [X] One branch per step in my `development-strategy.md`
- [X] A complete README

**Comment by harunaltunhr** [comment]
Updated Homework Issues

**Comment by snicoll** [comment]
@harunaltunhr this looks good. Please review the following:

* The link to your development strategy in the description above is broken. Please edit your comment and fix it
* The [html validation of the project](https://validator.w3.org/nu/?doc=https%3A%2F%2Fharunaltunhr.github.io%2Facme-web-design%2F) has triggered some warnings. Please review them and try to fix your HTML
* Your development strategy is quite complete, good job!

**Comment by harunaltunhr** [comment]
@snicoll fixed dev str link, fixed warnings. Could you please check in again?

**Comment by snicoll** [comment]
@harunaltunhr the link to your development strategy is stil broken, can you please fix it?

**Comment by snicoll** [comment]
Yay @harunaltunhr, well done!
