### ISSUE TITLE
Lisa Rosanty: Incremental Development, Week 1, homework

### ISSUE THREAD

**Issue by lisarosaa** [HackYourFutureBelgium/class-9-10#141]
# Week 1

## Incremental Development

- [assignments](https://github.com/HackYourFutureBelgium/incremental-development/tree/master/week-1#assignments)

## Prep Work
- [X] Git
- [X] Agile Development
- [X] Relative vs. Absolute Paths
- [X] Inspecting the DOM
- [X] HTML 5 Semantic Layout
---
### Isolate

- [x] `Team Branchies` [Live](https://lisarosaa.github.io/Letitbe-branches/.) [Source](https://github.com/lisarosaa/Letitbe-branches)

### Integrate

- [x] Semantic Layout [Live](https://lisarosaa.github.io/Exercise-Semantic-Layout/) [Source](https://github.com/lisarosaa/Exercise-Semantic-Layout)

---

### Suggested Study

- [x] Git & Github
- [x]  [HTML & CSS

### Exercises:

- [x] :egg: [html-css-git-exercises](https://github.com/hackyourfuturebelgium/html-css-git-exercises) - Week 1 [Source](https://github.com/lisarosaa/html-css-git-exercises/tree/red_links/week-1)
  - Fork & clone the repository
  - Complete the exercises in `week-1`
  - Push your work regularly to GitHub
- [ ]  :hatching_chick: [HTML-CSS-Practice-Problems](https://github.com/DevMountain/HTML-CSS-Practice-Problems)
- [ ]  :hatched_chick: [css-exercises](https://github.com/dangodev/css-exercises)

#### `acme-web-design`

- [x] [repo](https://github.com/lisarosaa/acme-web-design)
- [x] [live](https://lisarosaa.github.io/acme-web-design/)
- [x] [development-strategy](https://github.com/lisarosaa/acme-web-design/blob/master/development-strategy.md)
- [x] One branch per step in my `development-strategy.md`
- [x] A complete [README](https://github.com/lisarosaa/acme-web-design/blob/master/README.md)

**Comment by snicoll** [comment]
@lisarosaa great work. I've found a few things for you to look at:

* There are [some HTML validation errors](https://validator.w3.org/nu/?doc=https%3A%2F%2Flisarosaa.github.io%2Facme-web-design%2F) for your acme project
* Your development strategy has description starting with "As a user story". That should be the persona doing the action, e.g. "As a user of the site, "

**Comment by colevandersWands** [comment]
@lisarosaa , fixed!

**Comment by colevandersWands** [comment]
@lisarosaa , fixed!
