### ISSUE TITLE
Miroslav Veljanoski: working-with-code, week 1, review

### ISSUE THREAD

**Issue by miroslavveljanoski** [HackYourFutureBelgium/class-9-10#143]
# Sunday Review

__working-with-code, week 1__

## The Problem

- I don't know what to do and how to use vscode plugins? If it is possible some of the coaches to explain.

**Comment by otagi** [comment]
The plugins in VSCode are called _Extensions_. You can view them in the side bar with the menu _View > Extensions_ (on a Mac… might be slightly different on Windows or Linux).

<img width="544" alt="Capture d’écran 2020-05-17 à 10 47 46" src="https://user-images.githubusercontent.com/83604/82139926-077f7d00-982c-11ea-879e-8d71f4ef9da5.png">

To install one, search for it in the sidebar, and click its green _Install_ button. To uninstall, click its gear icon to show its options.

How to use them really depends on each extension. 

If it's one for a language, like Markdown, you don't have to do anything. It will just work whenever you edit a .md file.

Other extensions, like the one for git, might add a new interface in the sidebar, status bar, or menu. You'll have to look at the documentation the extension's developer provides to learn how to use it.

**Comment by miroslavveljanoski** [comment]
Thanks, Tiago :smiley:
