### ISSUE TITLE
Miroslav Veljanoski: incremental development, week 1, homework

### ISSUE THREAD

**Issue by miroslavveljanoski** [HackYourFutureBelgium/class-9-10#145]
# Week 1

## Incremental Development

- [Assignments](https://github.com/hackyourfuturebelgium/incremental-development/tree/master/week-1)

## Prep Work
- [X] Git
- [X] Agile Development
- [X] Relative vs. Absolute Paths
- [X] Inspecting the DOM
- [X] HTML 5 Semantic Layout

---

### Isolate

- [X] `Team Branchies` [live]( https://miroslavveljanoski.github.io/group-intro-with-branches/) [source](https://github.com/miroslavveljanoski/group-intro-with-branches)

### Integrate
- [x] `Semantic layout` [live]( https://miroslavveljanoski.github.io/semantic-layout/) [source](https://github.com/miroslavveljanoski/semantic-layout)
---

### Suggested Study
- [X] Git & GitHub
- [X] HTML & CSS
### Exercises
- [X] :egg: [html-css-git-exercises](https://github.com/miroslavveljanoski/html-css-git-exercises/tree/master/week-1) - Week 1
- [ ] :hatching_chick: [HTML-CSS-Practice-Problems](https://github.com/DevMountain/HTML-CSS-Practice-Problems)
- [ ] :hatched_chick: [css-exercises](https://github.com/dangodev/css-exercises)

### Project
project name: `acme-web-design` 

- [x] [repo](https://github.com/miroslavveljanoski/acme-web-design)
- [x] [live](https://miroslavveljanoski.github.io/acme-web-design/)
- [x] [development-strategy](https://github.com/miroslavveljanoski/acme-web-design/blob/master/development-strategy.md)
- [x] One branch per step in my `development-strategy.md`
- [x] A complete [README](https://github.com/miroslavveljanoski/acme-web-design/blob/master/README.md)

**Comment by snicoll** [comment]
This looks good overall, good job!

Here is what I've found:

* The [HTML validation](https://validator.w3.org/nu/?doc=https%3A%2F%2Fmiroslavveljanoski.github.io%2Fsemantic-layout%2F) of sematic layout has a warning
* There are warnings and errors for the [HTML validation](https://validator.w3.org/nu/?doc=https%3A%2F%2Fmiroslavveljanoski.github.io%2Facme-web-design%2F) of the acme web design


The development strategy is really used as a way to structure the work (potentially to split that work amongst a team). Having a user story that reads "As a visitor I want to see the style of the header" is a bit unusual. As a visitor, I don't want to see the style of the header but rather makes sure I can quickly identify the brand or something. It's not super important right now but keep in mind that those tasks should be a bit more high level and practical.

**Comment by miroslavveljanoski** [comment]
Hi @snicoll. 

Thanks for the suggestions, I already fix the errors from validation. I also made some modifications in the development strategy of the acme-web-design project.

I moved my issue back to the column "Ready for review" and hope that now is better. :smile:

**Comment by snicoll** [comment]
Thanks for the quick feedback @miroslavveljanoski. You're done for this week, congratulations!
