### ISSUE TITLE
feruz: incremental development, week 1, homework

### ISSUE THREAD

**Issue by Feruzteame** [HackYourFutureBelgium/class-9-10#146]
# Week 1

## Incremental  development

- [assignments](https://github.com/HackYourFutureBelgium/incremental-development/tree/master/week-1)

## Prep Work

- [x] Git
- [x] Agile Development
- [x] Relative vs. Absolute Paths 
- [x] Inspecting the DOM
- [x] HTML 5 Semantic Layout
---

### Isolate

- [x] a template development strategy
- [x] Team Branchies

### Integrate

- [x] [in-class-project]() (starter repository)
  - [x] [live](https://feruzteame.github.io/branches/)
  - [x] [repo](https://github.com/Feruzteame/branches)

---

### Suggested Study

- [x] Git & GitHub
- [x] HTML & CSS

#### Exercises:

- [ ] css-git-exercise [repo](https://github.com/Feruzteame/html-css-git-exercises),
- [x]  Html-css-practice-problem [repo](https://github.com/Feruzteame/HTML-CSS-Practice-Problems),
 [live level-1](https://feruzteame.github.io/HTML-CSS-Practice-Problems/level-1/index.html)
 [ live level-2](https://feruzteame.github.io/HTML-CSS-Practice-Problems/level-2/index.html)
 [live level-3](https://feruzteame.github.io/HTML-CSS-Practice-Problems/level-3/index.html)
- [x] css-Exercise [repo](https://github.com/Feruzteame/css-exercises)
   [live exercise-1](https://feruzteame.github.io/css-exercises/exercise-1/index.html)
   [live exercise-2](https://feruzteame.github.io/css-exercises/exercise-2/index.html)
   [live exercise-3](https://feruzteame.github.io/css-exercises/exercise-3/index.html)

### Project

Acem-web-design  project name:

- [x] [repo](https://github.com/Feruzteame/Acem-web-design)
- [x] [live](https://feruzteame.github.io/Acem-web-design/home.html)
- [x] [development-strategy](https://github.com/Feruzteame/Acem-web-design/blob/master/developmental-strategy.md)
- [x] One branch per step in my `development-strategy.md`
- [x] A complete README

**Comment by snicoll** [comment]
@Feruzteame this looks quite complete, good job!

Some feedback about branching:

* Each branch should be solely focused on one task from your development strategy. Looking at the structure of your branches, they mix several things. In your PRs I can see the task + a merge commit. It should only contain your task. We can discuss how to avoid the extra merge commit
* Although there is nothing wrong using PRs and Github to merge your work, try also to do that locally on your machine using whatever tool you fancy (vscode, gitkraken, command-line, etc). The purpose of this week's exercise is to understand the workflow locally on your machine.

Regarding your development strategy, it is well structured, nicely done. Try to provide a more narrowed/focused title for your task. "Working in home.html", for instance, does not really indicate what you're going to do. This document is for you but also serves as a reference for the project.

**Comment by snicoll** [comment]
@Feruzteame I've moved yours as the acme web design doesn't have the validation button on top. Please [review the instructions again](https://github.com/hackyourfuturebelgium/incremental-development/tree/master/week-1#acme-web-design) and make sure the [validation is available](https://github.com/HackYourFutureBelgium/w3-validation-template/blob/12a03b9ecdd010e4dc197376d7df732dbc14b2e3/index.html#L9).

**Comment by Feruzteame** [comment]
hi @snicoll 
thank you for your feedback.
ja, i forget the validation templet.
now i done the validation templet.
Can you check it please.

**Comment by snicoll** [comment]
@Feruzteame we're almost there. The link to your development strategy is 404ing. Can you please check? There is a typo in the file in your repo. It should be `development-strategy.md`.

**Comment by Feruzteame** [comment]
ja, now it works.

**Comment by Feruzteame** [comment]
I rename the file then it works.

**Comment by snicoll** [comment]
That's excellent @Feruzteame

**Comment by Feruzteame** [comment]
Thank you!
