### ISSUE TITLE
Iryna: working with code, Week 1

### ISSUE THREAD

**Issue by IrynaSpyrydonova** [HackYourFutureBelgium/class-9-10#15]
> !:warning:! Replace `your-user-name` with your actual GitHub user name and `repo-name` with the name of your class repo !:warning:!

- [x] :egg: [Group Intro Repo](https://github.com/IrynaSpyrydonova/group-intro)
- [x] :egg: Started my HYF Directory
- [x] :egg: _First Week on GitHub_
- [x] :egg: [My student bio](https://github.com/HackYourFutureBelgium/class-9-10/blob/master/student-bios/IrynaSpyrydonova.md)
- [x] :egg: [my `hack-my-future` repo](https://github.com/IrynaSpyrydonova/hack-my-future)
- [x] :egg: my markdown home page: [Live](https://irynaspyrydonova.github.io), [Source](https://github.com/IrynaSpyrydonova/IrynaSpyrydonova.github.io)
- [x] :egg: [My _Learnables_ Project Board](https://github.com/users/IrynaSpyrydonova/projects/2)

**Comment by colevandersWands** [comment]
@IrynaSpyrydonova, nice work. 💛

**Comment by colevandersWands** [comment]
@IrynaSpyrydonova , one detail.  Your `hack-my-future` repo was not started as a fork of ours: https://github.com/HackYourFutureBelgium/hack-my-future

you'll need to delete the one you created so you can fork ours

**Comment by IrynaSpyrydonova** [comment]
@colevandersWands Thank you. I made an adjustment.

**Comment by colevandersWands** [comment]
🎃
