### ISSUE TITLE
Sayed94h: Incremental development, week 1, homework

### ISSUE THREAD

**Issue by Sayed94h** [HackYourFutureBelgium/class-9-10#153]
# Week 1

## Incremental development

- [assignments](https://github.com/hackyourfuturebelgium/incremental-development/tree/master/week-1)

## Prep Work

- [x] Git
- [x] Agile Development
- [x] Relative vs Absolute paths
- [x] Inspecting the DOM
- [x] HTML5 Semantic Layout
---

## In Class

- [x] Isolate: I have understood the exercises
- [x] Integrate: [live](https://sayed94h.github.io/Development-strategy-semantic-layout/), [source](https://github.com/Sayed94h/Development-strategy-semantic-layout)

---

### Suggested Study

- [x] Git & GitHub
- [x] HTML & CSS

#### Exercises:

- [x] :egg: exercise 1: [repo](https://github.com/Sayed94h/html-css-git-exercises), [live](https://sayed94h.github.io/html-css-git-exercises/)
- [x] :hatching_chick: [HTML-CSS-Practice-Problems](https://github.com/DevMountain/HTML-CSS-Practice-Problems)
- [ ] :hatched_chick: [css-exercises](https://github.com/dangodev/css-exercises)
#### `acme-web-design`:

- [x] [repo](https://github.com/Sayed94h/acme-web-design)
- [x] [live](https://sayed94h.github.io/acme-web-design/)
- [x] [development-strategy](https://github.com/Sayed94h/acme-web-design/blob/master/development-strategy.md)
- [x] One branch per step in my `development-strategy.md`
- [x] A complete README

**Comment by colevandersWands** [comment]
@Sayed94h , very nice work overall!  I'm gonna get picky on this one.

In your development strategy you left __full user story description__ in each step.  Can you go back and fill in those phrases?  the idea here is to describe what value you are adding for the person visiting your site.  for example in the header step it might be something like _as a user I want to know what web site I am visiting_.  This link might be helpful: https://www.mountaingoatsoftware.com/agile/user-stories

**Comment by Sayed94h** [comment]
@colevandersWands  Thank you, I just added user stories for each step in development strategy.

**Comment by Sayed94h** [comment]
@snicoll  May I know why you removed the label 'ready-for-review' from this issue? As I read in the homework issue guide, when you move your issue to the 'ready-for-review' column then you have to give it a 'ready-for-review' label. Thanks

**Comment by snicoll** [comment]
@Sayed94h see slack for the explanation. Your card already states that your issue is ready in review when you move it to "ready for review".

**Comment by snicoll** [comment]
Great work @Sayed94h. As I've indicated today, the purpose of week1 was to practice `git merge` locally, not via Pull Requests. Please give that a try as well if you haven't already.
