### ISSUE TITLE
Olga Kozmovskaia: incremental-development, week 1

### ISSUE THREAD

**Issue by okozmovskaya** [HackYourFutureBelgium/class-9-10#154]
# Week 1

## Incremental-development

- [assignments](https://github.com/HackYourFutureBelgium/incremental-development/tree/master/week-1)

## Prep Work
- [x] Git
- [x] Agile Development
- [x] Relative vs Absolute
- [x] Inspecting the DOM
- [x] HTML 5 Semantic Layout

## In Class

- [x] Isolate: [team-branches](https://okozmovskaya.github.io/team-branches-group-2/), [source](https://github.com/okozmovskaya/team-branches-group-2)
- [x] Integrate: [semantic-layout](https://okozmovskaya.github.io/semantic-layout/), [source](https://github.com/okozmovskaya/semantic-layout)

### Suggested Study

- [x] Git & GitHub
- [x] HTML & CSS

#### Exercises:

- [x] 🥚 html-css-git-exercises - Week 1
- [x] 🐣 HTML-CSS-Practice-Problems

### Project

project Acme-Web-Design:

- [x] [repo](https://github.com/okozmovskaya/acme-web-design)
- [x] [live](https://okozmovskaya.github.io/acme-web-design/)
- [x] [development-strategy](https://github.com/okozmovskaya/acme-web-design/blob/master/development-strategy.md)
- [x] One branch per step in my `development-strategy.md`
- [x] A complete README

**Comment by otagi** [comment]
Good code, strategy, wireframes, and branches usage!

[Some HTML lines](https://github.com/okozmovskaya/acme-web-design/blob/master/services.html#L65-L78) have too much indentation, but that's a minor point in this exercise's context.

**Comment by okozmovskaya** [comment]
Thank you, Otagi!)))
I'll be more careful with indentation.
