### ISSUE TITLE
razvanbrb: incremental development, week 1, homework

### ISSUE THREAD

**Issue by razvanbrb** [HackYourFutureBelgium/class-9-10#155]
# Week 1

## Incremental Development

- [assignments](https://github.com/hackyourfuturebelgium/module-name/tree/master/week-1)

## Prep Work

- [x] [Review the Weekly Assignments guide ](https://home.hackyourfuture.be/students/weekly-assignments)
- [x] [Create your Homework Issue ](https://github.com/HackYourFutureBelgium/class-9-10/issues/155)

### Git

- [x] [Git & github for poets](https://www.youtube.com/watch?v=BCQHnlnPusY&list=PLRqwX-V7Uu6ZF9C0YMKuns9sLDzK6zoiV) 
- [x] [The Net Ninja](https://www.youtube.com/watch?v=QV0kVNvkMxc&list=PL4cUxeGkcC9goXbgTDQ0n_4TBzOO0ocPR&index=8) 
- [ ] [Understand how to use Atomic Commits](https://curiousprogrammer.io/blog/how-to-craft-your-changes-into-small-atomic-commits-using-git)

### Agile Development

- [x] Development Strategy (required)
- [x] [`development-strategy.md` files](https://home.hackyourfuture.be/students/development-strategy) example: [Team Branchies](https://github.com/HackYourFutureBelgium/team-branchies)
- [x] [What is this?](https://www.youtube.com/watch?v=GzzkpAOxHXs)
- [x] [Agile Development by Cartoon](https://www.youtube.com/watch?v=Z9QbYZh1YXY&list=PLBUu5aGDLKnbeEx8U-5r436bw6p9wv1rS)
- [x] [Splitting User Stories](https://www.youtube.com/watch?v=EDT0HMtDwYI)
- [ ] [The "what" not the "how"](https://duckduckgo.com/?q=what+are+user+stories&t=brave&iax=videos&ia=videos&iai=Pn-QMvDTuEY)
### Relative vs. Absolute Paths

- [x] [relative vs. absolute paths](https://www.youtube.com/watch?v=ephId3mYu9o)

### Inspecting the DOM

- [x] [How to inspect an element](https://www.lifewire.com/get-inspect-element-tool-for-browser-756549)
- [ ] [Modify the DOM. (does the source change?)](https://zapier.com/blog/inspect-element-tutorial/)

### HTML 5 Semantic Layout

- [ ] [study.hackyourfuture.be](https://study.hackyourfuture.be/html-css/html#semantic-layout)

---

### Isolate

- [x] `Team Branchies`
- [x] `A template development strategy`

### Integrate

- [x] [development strategy](../integrate/development-strategy-semantic-layout.md)
- [x] [wireframe](../integrate/wireframe.gif)
- [x] [starter repo](https://github.com/hackyourfuturebelgium/w3-validation-template) (project starter repo)

Example project to study: [separated](https://github.com/hackyourfuturebelgium/built-with-branches), [stepped](../integrate/all-about-trees-stepped)
---

#### Git & GitHub

- [x] [git & github for poets](https://www.youtube.com/watch?v=BCQHnlnPusY&list=PLRqwX-V7Uu6ZF9C0YMKuns9sLDzK6zoiV)
- [x]  [The Net Ninja](https://www.youtube.com/playlist?list=PL4cUxeGkcC9goXbgTDQ0n_4TBzOO0ocPR)
- [ ] [git-it](https://github.com/jlord/git-it-electron/)
- [x] [learngitbranching](https://learngitbranching.js.org)

#### HTML & CSS

- [x] [How to inspect an element](https://www.lifewire.com/get-inspect-element-tool-for-browser-756549)
- [ ] [Modify the DOM. (does the source change?)](https://zapier.com/blog/inspect-element-tutorial/)
- [ ] [inspecting-the-dom](https://hackyourfuture.be/inspecting-the-dom)
- [x] FCC, Responsive Web Design: [exercises](https://www.freecodecamp.org/learn), [video](https://www.youtube.com/watch?v=srvUrASNj0s)
- [ ] [mmtuts: HTML & CSS](https://www.youtube.com/watch?v=TKYsuU86-DQ&list=PL0eyrZgxdwhwNC5ppZo_dYGVjerQY3xYU)

#### Exercises:
- [x] :egg: [html-css-git-exercises](https://github.com/razvanbrb/html-css-git-exercises) - Week 1
  - [x] Fork & clone the repository
  - [x] Complete the exercises in `week-1`
  - [x] Push your work regularly to GitHub
- [x] :hatching_chick: [HTML-CSS-Practice-Problems](https://github.com/DevMountain/HTML-CSS-Practice-Problems)
- [ ] :hatched_chick: [css-exercises](https://github.com/dangodev/css-exercises)

#### `acme-web-design`

- [x] [repo](https://github.com/razvanbrb/acme-web-design)
- [x] [live](https://razvanbrb.github.io/acme-web-design/)
- [x] [development-strategy](https://github.com/razvanbrb/acme-web-design/tree/master/development-strategy.md)
- [x] One branch per step in my `development-strategy.md`
- [x] A complete README

**Comment by otagi** [comment]
Can you edit the links to your project's `repo` and `live` pages? They still are the template's placeholders. Thanks!

**Comment by razvanbrb** [comment]
Sorry. My bag.  I have edit the links now.

**Comment by otagi** [comment]
The code looks good!

A few remarks:
- The link to the live project has the old URL _and_ the new one glued together, so clicking it doesn't work.
- The links for the wireframe images in development-strategy.md are incorrect as well.
- From what I can see in your [network graph](https://github.com/razvanbrb/acme-web-design/network), you branched from master only the first time, instead of branching again from master for each feature branch. No need to redo the whole project (unless you have time), but don't hesitate to ask more questions if that process of branching is not 100% clear for you yet.

Can you correct the links problems? I will move the issue to "done" once these are ok.

**Comment by razvanbrb** [comment]
Hey Tiago. I have edited the link to live and the link for wireframes. Now is ok.

I have asked Olga if I can you here wireframes images. I was something wrong with my wireframes images to big or I don't know did not want to lose a lot of time on them. 



From what I can see in your network graph, you branched from master only the first time, instead of branching again from master for each feature branch. No need to redo the whole project (unless you have time), but don't hesitate to ask more questions if that process of branching is not 100% clear for you yet.

I did not understond what you mean from braching master only the first time.  And yes it's not 100% clear the branchig part :)

Thank you for your help and support!

**Comment by otagi** [comment]
Thank you for the updates, Razvan!

What I meant for the branches: in the network graph below, the blue line goes from `6` to `7`, which means `6` was the active branch, and `7` was created from there.

<img width="336" alt="razvan" src="https://user-images.githubusercontent.com/83604/83038506-52c03980-a03d-11ea-9979-37c024506ed4.png">

The better workflow is to first make `master` the active branch, and then create `7` from there. The graph should then display something like the red arrow.

Hope the explanation is clear enough. I know it's not always easy to understand concepts like these. Feel free to ask more questions if you want.

I'll mark this as done. You will have more occasions to practice branches in the next homeworks. 😉
