### ISSUE TITLE
Murielle: Incremental-development, week 1, homework

### ISSUE THREAD

**Issue by murvanessa** [HackYourFutureBelgium/class-9-10#157]
# Week 1

## Incremental Development

- [Assignments](https://github.com/hackyourfuturebelgium/incremental-development/tree/master/week-1)

## Prep Work
- [x] Git
- [x] Agile Development
- [x] Relative vs. Absolute Paths
- [x] Inspecting the DOM
- [x] HTML 5 Semantic Layout

---

### Isolate

- [X] `Team Branchies` [live](https://murvanessa.github.io/SkyBlueTeam/ ) [source](https://github.com/murvanessa/SkyBlueTeam )

### Integrate
- [X] `Semantic layout` [live](https://murvanessa.github.io/WebBranch/ ) [source](https://github.com/murvanessa/WebBranch )
---

### Suggested Study
- [X] Git & GitHub
- [X] HTML & CSS
### Exercises
- [X] :egg: [html-css-git-exercises](https://github.com/murvanessa/html-css-git-exercises/tree/master/week-1)
- [X] :hatching_chick: [HTML-CSS-Practice-Problems](https://github.com/murvanessa/HTML-CSS-Practice-Problems)
- [ ] :hatched_chick: [css-exercises](https://github.com/dangodev/css-exercises)

### Project
project name: `acme-web-design` 

- [X] [repo](https://github.com/murvanessa/acme-web-example)
- [X] [live](https://murvanessa.github.io/acme-web-example/)
- [X] [development-strategy](https://github.com/murvanessa/acme-web-example/blob/master/development-strategy.md)
- [X] One branch per step in my `development-strategy.md`
- [X] A complete [README](https://github.com/murvanessa/acme-web-example/blob/master/README.md)

**Comment by snicoll** [comment]
Well done @murvanessa!

I think your development strategy can be reviewed a bit. For instance the story for step 4 and step 5 are identical.

**Comment by snicoll** [comment]
@murvanessa  I've moved yours as the acme web design doesn't have the validation button on top. Please [review the instructions again](https://github.com/hackyourfuturebelgium/incremental-development/tree/master/week-1#acme-web-design) and make sure the [validation is available](https://github.com/HackYourFutureBelgium/w3-validation-template/blob/12a03b9ecdd010e4dc197376d7df732dbc14b2e3/index.html#L9).

**Comment by snicoll** [comment]
@murvanessa thanks for the update. There are [a number of errors](https://validator.w3.org/nu/?doc=https%3A%2F%2Fmurvanessa.github.io%2Facme-web-example%2F) triggered by the "validate html" button. Please review them and adapt your HTML accordingly.

**Comment by murvanessa** [comment]
hello i have change 😟

**Comment by snicoll** [comment]
That's great @murvanessa. You're done for this week, congratulations!
