### ISSUE TITLE
Mohammad Musa: Incremental Development, week 1, homework

### ISSUE THREAD

**Issue by Mohammad-Musa** [HackYourFutureBelgium/class-9-10#159]
# Week 1

## Incremental Development

- [assignments](https://github.com/HackYourFutureBelgium/incremental-development/blob/master/week-1/README.md)

## Prep Work

- ## Git
  - [x] [git & github for poets](https://www.youtube.com/watch?v=BCQHnlnPusY&list=PLRqwX-V7Uu6ZF9C0YMKuns9sLDzK6zoiV)
  - [x] [The Net Ninja](https://www.youtube.com/watch?v=QV0kVNvkMxc&list=PL4cUxeGkcC9goXbgTDQ0n_4TBzOO0ocPR&index=8)
  - [x] [Understand how to use Atomic Commits](https://curiousprogrammer.io/blog/how-to-craft-your-changes-into-small-atomic-commits-using-git/)
- ## Agile Development
  - [x] **Development Strategy (required) -** [development-strategy.md files](https://home.hackyourfuture.be/students/development-strategy) **- example:** [Team Branchies](https://github.com/HackYourFutureBelgium/team-branchies)
  - [x] [What is this?](https://www.youtube.com/watch?v=GzzkpAOxHXs)
  - [x] [Agile Development by Cartoon](https://www.youtube.com/watch?v=Z9QbYZh1YXY&list=PLBUu5aGDLKnbeEx8U-5r436bw6p9wv1rS)
  - [x] [Splitting User Stories](https://www.youtube.com/watch?v=EDT0HMtDwYI)
  - [x] [The "what" not the "how"](https://duckduckgo.com/?q=what+are+user+stories&t=brave&iax=videos&ia=videos&iai=Pn-QMvDTuEY)
- ## Relative vs. Absolute Paths
  - [x] [relative vs. absolute paths](https://www.youtube.com/watch?v=ephId3mYu9o) 
- ## Inspecting the DOM
  - [x] [How to inspect an element](https://www.lifewire.com/get-inspect-element-tool-for-browser-756549)
  - [x] [Modify the DOM. (does the source change?)](https://zapier.com/blog/inspect-element-tutorial/)
- ## HTML 5 Semantic Layout
  - [x] [study.hackyourfuture.be](https://study.hackyourfuture.be/html-css/html#semantic-layout)
---

- ## In Class

  - [x] **Team Branching :** [live](https://mohammad-musa.github.io/Group-Branches/)  [source](https://github.com/Mohammad-Musa/Group-Branches/edit/master/README.md)

---

### Suggested Study

- ### Git & GitHub
  - [x] [git & github for poets](https://www.youtube.com/watch?v=BCQHnlnPusY&list=PLRqwX-V7Uu6ZF9C0YMKuns9sLDzK6zoiV)
  - [x] [The Net Ninja](https://www.youtube.com/playlist?list=PL4cUxeGkcC9goXbgTDQ0n_4TBzOO0ocPR)
  - [x] [git-it](https://github.com/jlord/git-it-electron/)
  - [x] [Learn Git Branching](https://learngitbranching.js.org/)

#### Exercises:

- [X] :egg: exercise 1: [repo](https://github.com/Mohammad-Musa/html-css-git-exercises), [live]( https://mohammad-musa.github.io/html-css-git-exercises/)

### Project

**Acme Web Design**

- [x] [repo](https://github.com/Mohammad-Musa/acme-web-design)
- [x] [live](https://mohammad-musa.github.io/acme-web-design/)
- [x] [development-strategy](https://github.com/Mohammad-Musa/acme-web-design/blob/master/development-strategy.md)
- [x] One branch per step in my `development-strategy.md`
- [x] A complete [README](https://github.com/Mohammad-Musa/acme-web-design/blob/master/README.md)

**Comment by colevandersWands** [comment]
Very well done!  Many, well-defined steps in your development strategy and lots of small branches for each change.  
I like the Extra section in each step of your strategy - there's always something unexpected that comes up and this is a nice way to deal with that

There's just 2 HTML validation errors (the same error), once on _about_ and once on _services.  But not enough to keep this from DONE

**Comment by Mohammad-Musa** [comment]
@colevandersWands Thank you :)
