### ISSUE TITLE
Fatih: incremental-development, week 1, homework

### ISSUE THREAD

**Issue by fmkarakus** [HackYourFutureBelgium/class-9-10#165]
# Week 1

## incremental-development

- [assignments](https://github.com/HackYourFutureBelgium/incremental-development/tree/master/week-1)

## Prep Work

- [x] Git
- [x] Agile Development
- [x] Relative vs. Absolute Paths
- [x] Inspecting the DOM
- [x] HTML 5 Semantic Layout

---

## In Class

  - [x] **Isolate:** [Team Branching](https://github.com/fmkarakus/team-branchies/network) **&** [Development Strategy](https://github.com/fmkarakus/team-branchies/blob/master/development-strategy.md)
  - [x] **Integrate:** [live](https://fmkarakus.github.io/integrate2), ! [source](https://github.com/fmkarakus/integrate2)

---

### Suggested Study

- [ ] Git & GitHub
- [ ] HTML & CSS

### Exercises:

- [x] `🥚` exercise 1: [repo](https://github.com/fmkarakus/html-css-git-exercises), [live](https://your-user-name.github.io/exercise-name/)
- [x] `🐣` exercise 2: [repo](https://github.com/your-user-name/exercise-name), [live](https://your-user-name.github.io/exercise-name/)
- [ ] `🐥' exercise 3: ....

### Project

project name:

- [x] [repo](https://github.com/fmkarakus/acme-web-design)
- [x] [live](https://fmkarakus.github.io/acme-web-design)
- [x] [development-strategy](https://github.com/fmkarakus/acme-web-design/blob/master/development-strategy.md)
- [x] One branch per step in my `development-strategy.md`
- [x] A complete [README.md](https://github.com/fmkarakus/acme-web-design/blob/master/README.md)

**Comment by colevandersWands** [comment]
@fmkarakus , a few HTML validation errors. otherwise very good!

your network graph looks great

**Comment by fmkarakus** [comment]
Hi @colevandersWands,
This issue is closed and then reopened and moved from "Done" to "Needs Revision". Can you tell me what should I change exactly?  Thanks.

**Comment by colevandersWands** [comment]
@fmkarakus , this was just clumsyness on my part. The project board was laggy so I accidentally moved the wrong issues for a while. You're good to go! i've moved your issue to DONE
