### ISSUE TITLE
yildiraykoyuncu: working with code, Week 1

### ISSUE THREAD

**Issue by yildiraykoyuncu** [HackYourFutureBelgium/class-9-10#17]
- [x] :egg: [Group Intro Repo](https://github.com/yildiraykoyuncu/group-intro-9-10-1)
- [x] :egg: Started my HYF Directory
- [x] :egg: _First Week on GitHub_
- [x] :egg: [My student bio](https://github.com/HackYourFutureBelgium/class-9-10/blob/master/student-bios/yildiraykoyuncu.md)
- [x] :egg: [my `hack-my-future` repo](https://github.com/yildiraykoyuncu/hack-my-future)
- [x] :egg: my markdown home page: [Live](https://yildiraykoyuncu.github.io/my-bio/), [Source](https://github.com/yildiraykoyuncu/my-bio)
- [x] :egg: [My _Learnables_ Project Board](https://github.com/users/yildiraykoyuncu/projects/1)

**Comment by colevandersWands** [comment]
🦅
