### ISSUE TITLE
Galal KORO: Incremental Development, week 1, homework

### ISSUE THREAD

**Issue by galalkoro** [HackYourFutureBelgium/class-9-10#179]
# Week 1

## Incremental Development
- [assignments](https://github.com/hackyourfuturebelgium/Incremental-Development/tree/master/week-1)

## Prep Work

- [x] Git
- [x] Agile Development
- [x] Relative vs. Absolute Paths
- [x] Inspecting the DOM
- [x] HTML 5 Semantic Layout

---

## In Class

- [x] Isolate: I have understood the exercises
- [ ] Integrate: [live](), [source](https://github.com/galalkoro/let-it-be-6)

---

### Suggested Study

- [x] Git & GitHub
- [x] HTML & CSS

### Exercises:

- [x] 🥚 html-css-git-exercises: [repo](https://github.com/galalkoro/html-css-git-exercises), [live](https://your-user-name.github.io/html-css-git-exercises/)
- [ ] 🐣  [repo](https://github.com/your-user-name/exercise-name), [live](https://your-user-name.github.io/exercise-name/)
- [ ] 🐥 [css-exercises]()

### Project

acme-web-design

- [x] [repo](https://github.com/galalkoro/acme-web-design)
- [x] [live](https://galalkoro.github.io/acme-web-design/index.html)
- [ ] [development-strategy]()
- [ ] One branch per step in my `development-strategy.md`
- [ ] A complete README

**Comment by snicoll** [comment]
@galalkoro if you think you're done please move that card to "Ready for review".
