### ISSUE TITLE
Sharaf: Working with code, Week 1

### ISSUE THREAD

**Issue by sharafcs50** [HackYourFutureBelgium/class-9-10#18]
- [x] :egg: [Group Intro Repo](https://github.com/sharafcs50/group-intro)
- [x] :egg: Started my HYF Directory
- [x] :egg: _First Week on GitHub_
- [x] :egg: [My student bio](https://github.com/hackyourfuturebelgium/class-9-10/tree/master/student-bios/sharafcs50.md)
- [x] :egg: [my `hack-my-future` repo](https://github.com/sharafcs50/hack-my-future)
- [x] :egg: my markdown home page: [Live](https://sharafcs50.github.io), [Source](https://github.com/sharafcs50/sharafcs50.github.io)
- [x] :egg: [My _Learnables_ Project Board](https://github.com/users/sharafcs50/projects/1)

**Comment by colevandersWands** [comment]
@sharafcs50 good move starting on your _learnables_ already, this makes it very helpful for us to know what you need help with

Just a little thing left, the link to your student bio opens to a 404 page

**Comment by colevandersWands** [comment]
🌵
