### ISSUE TITLE
Yana: Incremental Development, Week 1

### ISSUE THREAD

**Issue by adekimpianna** [HackYourFutureBelgium/class-9-10#186]
# Wednesday Check-In

__Incremental Development, WEEK 1__

## Progress

Completed the two projects from the last Sunday class.

## Blocked

* I feel good with Gitkraken but I feel **an urge to learn Command line** too because my friends are using it. Will we need the Command line or will it be the best tool to be used for the incoming modules?
* Some are blocked on the EGG exercise. Well, I just rightly want to start it now, so I don't have any idea yet how hard it will be. I will update this issue if I am blocked too!

## Next Steps

* I will do the rest of this week homework, start the big acme project right afterwards. 
* I want to dig more about CSS, like a lot of it!! I wanted to do something with the responsive text but it did not work, so I had to let go of my will and did it another way. 
* I will dig and try to learn the command line 😅 

## Tip(s) of the week

Self-talk: We have our own pace and our own way of learning. Don't stress out, do it step by step 🥰

**Comment by snicoll** [comment]
@adekimpianna we can have a look to some command-line tips and tricks.
