### ISSUE TITLE
Harun Altun: working with code, Week 1

### ISSUE THREAD

**Issue by harunaltunhr** [HackYourFutureBelgium/class-9-10#19]
> !:warning:! Replace `your-user-name` with your actual GitHub user name and `repo-name` with the name of your class repo !:warning:!

- [X] :egg: [Group Intro Repo](https://github.com/harunaltunhr/group-intro)
- [X] :egg: Started my HYF Directory
- [X] :egg: _First Week on GitHub_
- [X] :egg: [My student bio](https://github.com/hackyourfuturebelgium/class-9-10/tree/master/student-bios/harunaltunhr.md)
- [X] :egg: [my `hack-my-future` repo](https://github.com/harunaltunhr/hack-my-future)
- [X] :egg: my markdown home page: [Live](https://harunaltunhr.github.io), [Source](https://github.com/harunaltunhr/harunaltunhr.github.io)
- [X] :egg: [My _Learnables_ Project Board](https://github.com/users/harunaltunhr/projects/1)

**Comment by harunaltunhr** [comment]
Revised

**Comment by colevandersWands** [comment]
One picky detail: don't forget to add your issue to the `working-with-code` milestone!

**Comment by harunaltunhr** [comment]
Added milestone

**Comment by colevandersWands** [comment]
✌️
