### ISSUE TITLE
Mari: Incremental development, week 1

### ISSUE THREAD

**Issue by Meowri** [HackYourFutureBelgium/class-9-10#192]
# Wednesday Check-In

__Incremental development, week 1__

## Progress

I was exceptionally stuck this week, I am finding the [Exercise started on Sunday - w3-validation-template] (https://github.com/Meowri/incremental-development-excersise-2) really challenging.
and I could not connect to the Wednesday session from work even though I am lost, and I found that very frustrating.
I took the night to gather myself and start fresh, I will attempt to progress today past my block.

## Blocked

Incorporating CSS and HTML on two separate documents, I struggled to move from in-line styling to this.

## Next Steps

TIME! I am going to get this I just need some time
and ask a coach to talk to me on Sunday as a re-cap from this week

## Tip(s) of the week

No yet, I thought going back and re-capping on the previous week, would help me, but it did not.

**Comment by colevandersWands** [comment]
@Meowri , create an issue for tomorrow with your questions. We'll find it with the `sunday-review` label

And don't worry so much about feeling behind.  What you described are exactly what you should be struggling with at this point in the course.  The lesson plan and homework for this week will be very similar to last week so you'll have time to keep practicing these same skills before moving on

**Comment by Meowri** [comment]
Thank you very much for your encouraging comment!
