### ISSUE TITLE
HazemBittar: Incremental-development, week 1, homework

### ISSUE THREAD

**Issue by HazemBittar** [HackYourFutureBelgium/class-9-10#195]
# Week 1

## Incremental  development

- [assignments](https://github.com/HackYourFutureBelgium/incremental-development/tree/master/week-1)
## Prep Work

- [x] Git
- [x] Agile Development
- [x] Relative vs. Absolute Paths 
- [x] Inspecting the DOM
- [x] HTML 5 Semantic Layout

---

## In Class

- [x] Isolate: I have understood the exercises
- [x] Integrate: [live](https://hazembittar.github.io/semantic-layout/ ), [source](https://github.com/HazemBittar/semantic-layout-excirses )

---

### Suggested Study

- [x] Git & GitHub
- [x] HTML & CSS

### Exercises:

- [x] :egg: html-css-git-exercises: [repo](https://github.com/HazemBittar/html-css-git-exercises/tree/master/week-1)
- [x] :hatching_chick: HTML- CSS-practice- ptoblem [repo](https://github.com/HazemBittar/HTML-CSS-Practice-Problems/tree/master/level-1), 

### Project

project name:Acem-web-design 

- [x] [repo](https://github.com/HazemBittar/acm-webdesign)
- [x] [live](https://hazembittar.github.io/acm-webdesign/)
- [x] [development-strategy](https://github.com/HazemBittar/acm-webdesign/blob/master/development-strategy.md)
- [x] One branch per step in my `development-strategy.md`
- [x] A complete README

**Comment by otagi** [comment]
The style.css is not applied to your index.html in the [live project](https://hazembittar.github.io/acme-web-design/). 

Check your [link line](https://github.com/HazemBittar/acme-web-design/blob/master/index.html#L10): `<link rel="stylesheet" href="./css/style.css">` is looking for a stylesheet in the `css/` sub-folder, but your stylesheet is in the main folder.

**Comment by HazemBittar** [comment]
I updated the styles sheet

**Comment by HazemBittar** [comment]
check it out coach @otagi

**Comment by otagi** [comment]
The code is sound. Good work! 

There are only [2 commits](https://github.com/HazemBittar/acm-webdesign/commits/master) on this project, though. Is there a reason why we don't see the usual branches for the user stories?

**Comment by HazemBittar** [comment]
Because i coding offline most of time in laptop and push all works once using another laptop at home

**Comment by otagi** [comment]
Ok, I understand.

Do you think you will have to continue working on a separate offline computer? It will be a problem in the coming weeks, when you start coding with a team. You will need to work on the full shared git project at all times, to stay in sync with your teammates’ commits.

**Comment by HazemBittar** [comment]
I solve the problem by now I will working online to keep update with mates! :relaxed:
