### ISSUE TITLE
Harun : incremental-development, week 2, homework

### ISSUE THREAD

**Issue by harunaltunhr** [HackYourFutureBelgium/class-9-10#196]
# Week 2

## incremental-development

- [assignments](https://github.com/hackyourfuturebelgium/incremental-development/tree/master/week-2)

## Prep Work

- [X] Collaborating on GitHub
- [X] WireFrames
- [X] Pair Programming

---

## In Class

- [X] Isolate: I have understood the exercises [live](https://miroslavveljanoski.github.io/miroslav-harun/),  [source](https://github.com/miroslavveljanoski/miroslav-harun/tree/master)
- [X] Integrate: [live](https://harunaltunhr.github.io/integrate-week2/), [source](https://github.com/harunaltunhr/integrate-week2)

---

### Suggested Study

- [X] Git & GitHub
- [X] Responsive Design
- [X] CLI
### Exercises:

- [X] :egg: html-css-git-exercises-Week2 : [repo](https://github.com/harunaltunhr/html-css-git-exercises)
- [X] :hatching_chick: HTML-CSS-Practice-Problems: [repo](https://github.com/harunaltunhr/HTML-CSS-Practice-Problems/tree/master/level-2),
- [ ] :hatched_chick: css exercises: [repo](https://github.com/harunaltunhr/HTML-CSS-Practice-Problems/tree/master/level-2)
### Project

`code-along`
- [X] [repo](https://github.com/harunaltunhr/app-theme)
- [X] [live](https://harunaltunhr.github.io/app-theme/ )
- [X] [development-strategy](https://github.com/harunaltunhr/app-theme/blob/master/development-strategy.md)
- [X] One branch per step in my `development-strategy.md`
- [X] One closed Issue per step in my `development-strategy.md`
- [X] One closed Pull Request per step in my `development-strategy.md`
- [X] A complete README

**Comment by snicoll** [comment]
Great job @harunaltunhr 

A few remarks:

* Regarding your development strategy, you are not the persona so your user stories should not start with "I want". The purpose of a user story is to describe the feature and who will benefit from it. Something like "As a user of the site, I ...". Later one you'll have additional persona. For instance "As an admin of the site, I want to see the last 10 orders".
* Please don't add "Closes #id" on the same line as the title of the commit. 
* Take the habit of providing a proper title for each issue. I know it is a bit artificial given the current exercise but you should see an issue as a reference of the work. [This issue for instance](https://github.com/harunaltunhr/app-theme/issues/2) doesn't really tell me what the purpose of the task is. 

Can you please review your development strategy and review your issues to provide a bit more context in each (the content of development strategy should help you). As the work is done, you can just add additional commits, no need to redo your commits or the PRs of  course :)

**Comment by harunaltunhr** [comment]
Thank you @snicoll for advise... I changed development-strategy and add comment to all issues. Next time, I will be more careful

**Comment by snicoll** [comment]
Alright. I think your issue titles could be edited as well to better convey what each means. By I think that's a detail we can improve going forward.
