### ISSUE TITLE
Aleksandra: Incremental development, week 2, homework

### ISSUE THREAD

**Issue by aleks2407** [HackYourFutureBelgium/class-9-10#199]
# Aleks2407

## Prep Work

- [x] Collaborating on GitHub
- [x] WireFrames
- [x] Pair Programming

## Lesson 
- [x] Isolate: I understood 
- [x] Integrate: [source](https://github.com/ms-np/wireframe_group-work), [live](https://ms-np.github.io/wireframe_group-work/) 

## Suggested Study
- [x] Git & GitHub
- [x] Responsive Design
- [x] CLI

### Exercises

- [x] :egg: [html-css-git-exercises](https://github.com/aleks2407/html-css-git-exercises/tree/master/week-2) Week 2
- [ ] :hatching_chick: [HTML-CSS-Practice-Problems](https://github.com/DevMountain/HTML-CSS-Practice-Problems)
- [ ] :hatched_chick: [css-exercises](https://github.com/dangodev/css-exercises)

#### `app-theme`

- [x] [source: HYF-app-theme](https://github.com/aleks2407/HYF-app-theme)
- [x] [live](https://aleks2407.github.io/HYF-app-theme/contact.html)
- [x] [development-strategy](https://github.com/aleks2407/HYF-app-theme/blob/master/development-strategy.md)
- [x] One branch per step in my `development-strategy.md`
- [x] One closed Issue per step in my `development-strategy.md`
- [x] One closed Pull Request per step in my `development-strategy.md`
- [x] A complete [README](https://github.com/aleks2407/HYF-app-theme/blob/master/README.md)

**Comment by snicoll** [comment]
Excellent work @aleks2407.
