### ISSUE TITLE
Mamé: incremental-development, week2, homework

### ISSUE THREAD

**Issue by mametur** [HackYourFutureBelgium/class-9-10#200]
### Collaborating on GitHub
- [x] Git Workflow for 2
- [x] Pull Requests
- [x] Git & GitHub for Poets: pull request & merge, resolving conflicts
- [x] The Net Ninja: 11, 12
- [x] Pull Request Reviews: about them, requesting one

## Lesson 
 - [x] Isolate: I have understood the exercises
- [x] Integrate: [live](https://mametur.github.io/mame-oguz-work/), [source](https://github.com/mametur/mame-oguz-work)

### Exercises

- [x] :egg: [html-css-git-exercises](https://github.com/mametur/html-css-git-exercises/tree/master/week-2) Week 2
- [ ] :hatching_chick: [HTML-CSS-Practice-Problems](https://github.com/DevMountain/HTML-CSS-Practice-Problems)
- [ ] :hatched_chick: [css-exercises](https://github.com/dangodev/css-exercises)

#### `app-theme`

- [x] [repo](https://github.com/mametur/app-theme)
- [x] [live](https://mametur.github.io/app-theme/)
- [x] [development-strategy](https://github.com/mametur/app-theme/blob/master/development-strategy.md)
- [x] One branch per step in my `development-strategy.md`
- [x] One closed Issue per step in my `development-strategy.md`
- [x] One closed Pull Request per step in my `development-strategy.md`
- [x] A complete README

**Comment by snicoll** [comment]
Good work @mametur. I've added a few comments in your repos.
