### ISSUE TITLE
Pavel: Incremental Development-2,  homework

### ISSUE THREAD

**Issue by pavelbidenko2018** [HackYourFutureBelgium/class-9-10#201]
# Week 2

## Incremental Development

- [assignments](https://github.com/HackYourFutureBelgium/incremental-development/tree/master/week-2#assignments)

## Prep Work

- [x] Collaborating on GitHub
- [x] WireFrames
- [x] Pair Developing

---

## In Class

- [x] Isolate: I have understood the exercises
- [x] Integrate WEEK2 (pair development): [live](https://fmkarakus.github.io/pair-integrate/), [source](https://github.com/fmkarakus/pair-integrate)

---

### Suggested Study

- [x] [git & github for poets](https://www.youtube.com/watch?v=BCQHnlnPusY&list=PLRqwX-V7Uu6ZF9C0YMKuns9sLDzK6zoiV)
- [x] [git-it](https://github.com/jlord/git-it-electron/) 

### Exercises:

- [x] :egg: html-css-git-exercises - WEEK2: [repo](https://github.com/pavelbidenko2018/html-css-git-exercises/tree/master/week-2)
- [ ]  :hatching_chick: exercise 2: [repo](https://github.com/your-user-name/exercise-name), [live](https://your-user-name.github.io/exercise-name/)

### Project

project name:

- [x] [repo](https://github.com/pavelbidenko2018/app-theme)
- [x] [live](https://pavelbidenko2018.github.io/app-theme/)
- [x] [development-strategy](https://github.com/pavelbidenko2018/app-theme/blob/master/development-strategy.md)
- [x] One branch per step in my `development-strategy.md`
- [x] One closed Issue per step in my `development-strategy.md`
- [x] One closed Pull Request per step in my `development-strategy.md`
- [x] A complete [README](https://github.com/pavelbidenko2018/app-theme/blob/master/README.md)

**Comment by snicoll** [comment]
Reminder. No need to `ready-for-review` label :)

**Comment by snicoll** [comment]
@pavelbidenko2018 good work, nice experiment with the GitHub infra in your `app-theme` project!

Your development strategy is still too much focused on the technical. The title of each story should describe the feature and not what you're technically doing to implement the feature. There is no need for "On this step" either, look at existing development strategies for reference.

**Comment by pavelbidenko2018** [comment]
@snicoll thank you very much for the review and feedback! Feeling even more motivated )
