### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by abelRoland** [HackYourFutureBelgium/class-9-10#204]
Some broken links that I found when studying:

|Page|Link|
|-----|----|
|[Class 9-10 Home](https://github.com/HackYourFutureBelgium/class-9-10/blob/master/README.md)|[HYF Home](https://home.hackyourfuture.be/home)|
|[HYF Study](https://github.com/HackYourFutureBelgium/study/blob/master/html-css/css.md)|[Flexbox Zombies](https://mastery.games/p/flexbox-zombies)|

**Comment by colevandersWands** [comment]
@abelRoland , can you send a pull request?  you can link it to this issue ([guide](https://help.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords))

**Comment by abelRoland** [comment]
🦄 :
