### ISSUE TITLE
razvanbrb: incremental development, week 2, homework

### ISSUE THREAD

**Issue by razvanbrb** [HackYourFutureBelgium/class-9-10#205]
# Week 2

## Incremental Development

- [assignments](https://github.com/HackYourFutureBelgium/incremental-development/tree/master/week-2)

## Prep Work

- [x] Collaborating on GitHub
- [x] WireFrames
- [x] Pair Programming

---

## In Class

- [x] Isolate: [live]( https://razvanbrb.github.io/workflow-workshop/), [source]( https://github.com/razvanbrb/workflow-workshop/)
- [ ] Integrate: [live](), [source]()

---

### Suggested Study

- [x] Git & GitHub
- [x] Responsive Design
- [x] CLI

### Exercises:

- [x] :egg: html-css-git-exercises week 2: [repo](https://github.com/razvanbrb/html-css-git-exercises/tree/master/week-2), [live](https://razvanbrb.github.io/html-css-git-exercises/)
- [x] :hatching_chick: HTML-CSS-Practice-Problems: [repo](https://github.com/razvanbrb/HTML-CSS-Practice-Problems), [live]( https://razvanbrb.github.io/HTML-CSS-Practice-Problems/)
- [ ] :hatching_chick: css-exercises: [repo](https://github.com/your-user-name/exercise-name), [live](https://your-user-name.github.io/exercise-name/)

#### `app-theme`:

- [x] [repo]( https://github.com/razvanbrb/app-theme-2)
- [x] [live]( https://razvanbrb.github.io/app-theme-2/)
- [x] [development-strategy](https://github.com/razvanbrb/app-theme-2/blob/master/development-strategy.md)
- [x] One branch per step in my `development-strategy.md`
- [x] A complete README

**Comment by otagi** [comment]
Good code overall!

The HTML validation for index.html has some errors. Can you fix these?

**Comment by razvanbrb** [comment]
Hey Tiago. I have made the validation changed. Now it should be ok. Thank you for you help and support! I appreciate it.
