### ISSUE TITLE
Mari: incremental-development-excersise, week 1- review

### ISSUE THREAD

**Issue by Meowri** [HackYourFutureBelgium/class-9-10#206]
# Sunday Review

__incremental-development-excersise, week 1__

## The Code

The code you want to review, included as:

- w3-validation-template - [Repo link](https://github.com/Meowri/incremental-development-excersise-2) 

## The Problem

Explain the situation:

When I try to click on the link for the live site it directed me to the Markdown file as the main display and did not prioritize displaying the HTML code.
I made some changes to see if I can get it to prioritize displaying the HTML file above the readme and broke something 
[live site 404 file not found] (https://meowri.github.io/incremental-development-excersise-2/)

I tried to re-create a live page and eventually decided to create a new branch and try to get that one to work, but too be honest, I am very unsure what I even broke?
- What _does_ the code do
Error file not found on live site
- What do you _want_ it to do
Prioritize display of HTML file not README.MD
Also display CSS, if it gets that far
- How do you think it works?
I think I am missing something I should understand something on my HTML file
- What don't you understand about how it works?
Why it would not load all the different files together, and if a ReadMe is important to understand the project or is that the first displaypage/body page of your site?

## Best Efforts

Explain what you've tried so far:

- Include code
- Include everything you tried, even if it seems silly to you
I tried changing the file names around, giving CSS and HTML matching names or called the CSS styles, I tried creating a wireframe display with the read me, I tried to get rid of the MD files and readme?
- What happened with each effort?
No changes until I got error 404, re-added read me but still have the error
- What brought you closer?
*Still in progress* Starting from scratch- re-tracing and dissecting my steps
- What brought you farther?
*Still in progress* Will update 

## Helpful Links

*Still in progress* Will update 

## Hopeful Links

*Still in progress* Will update

**Comment by colevandersWands** [comment]
@Meowri , I forked your repo and was able to make it work with one tiny change.  can you find it?  

* https://colevanderswands.github.io/incremental-development-excersise-2/
* https://colevanderswands.github.io/incremental-development-excersise-2/

(hint: your student bio)

When you turn on github pages and set it to master branch it tries to host these files, with this priority

1. `index.html`
2. `README.md`

otherwise there's a 404

**Comment by Meowri** [comment]
Thank you, the session today helped solve this last issue and the links you sent really helped me understand.
