### ISSUE TITLE
Murielle: working with code, Week 1

### ISSUE THREAD

**Issue by murvanessa** [HackYourFutureBelgium/class-9-10#21]
# Prep Work
- [x]  Git & GitHub for Poets
- [x]   Homework Submission Process
- [x]   the HYF Be Precourse

# Assignments
- [x] :egg: [Group Intro Repo](https://github.com/murvanessa/Sky-Blue) [live Demo](https://murvanessa.github.io/Sky-Blue/)
- [x] :egg: Started my HYF Directory
- [x] :egg: _First Week on GitHub_
- [x] :egg: [My student bio](https://github.com/HackYourFutureBelgium/class-9-10/blob/master/student-bios/murvanessa.md)
- [x] :egg: [my `hack-my-future` repo](https://github.com/murvanessa/hack-my-future)
- [x] :egg: my markdown home page: [Live](https://murvanessa.github.io/), [Source](https://github.com/murvanessa/murvanessa.github.io)
- [x] :egg: [My _Learnables_ Project Board](https://github.com/users/murvanessa/projects/2)

**Comment by colevandersWands** [comment]
@murvanessa , your project board link is still empty: https://github.com/murvanessa?tab=projects

Otherwise all good!  Nice work with the group intro and home page

**Comment by colevandersWands** [comment]
@murvanessa , a detail I missed on the first check.  can you rename your student bio link so it matches your github user name?  this way we can find it from the class home page: https://hackyourfuture.be/class-9-10/?student=murvanessa
