### ISSUE TITLE
Fatih: incremental development, week 2, homework

### ISSUE THREAD

**Issue by fmkarakus** [HackYourFutureBelgium/class-9-10#212]
# Week 2

## Incremental Development

- [assignments](https://github.com/hackyourfuturebelgium/incremental-development/tree/master/week-2)

## Prep Work

- [x] Collaborating on GitHub
- [x] WireFrames
- [x] Pair Programming

---

## In Class

- [x] Isolate: I have understood the exercises
- [x] Integrate: [live](https://fmkarakus.github.io/pair-integrate), [source](https://github.com/fmkarakus/pair-integrate)

---

### Suggested Study

- [ ] Git & GitHub
- [x] Responsive Design
- [ ] CLI

### Exercises:

- [x] :egg: html-css-git-exercises - Week 2 : [repo](https://github.com/fmkarakus/html-css-git-exercises/tree/master/week-2)
- [x] :hatching_chick:  HTML-CSS-Practice-Problems : [repo](https://github.com/fmkarakus/HTML-CSS-Practice-Problems)
- [ ] :hatched_chick:   css-exercises : [repo](https://github.com/your-user-name/exercise-name), [live](https://your-user-name.github.io/exercise-name/)

### Project

Project name: App-Theme

- [x] [repo](https://github.com/fmkarakus/app-theme)
- [x] [live](https://fmkarakus.github.io/app-theme)
- [x] [development-strategy](https://github.com/fmkarakus/app-theme/blob/master/development-strategy.md)
- [x] [One branch per step in `development-strategy.md`](https://github.com/fmkarakus/app-theme/network)
- [x] [One closed Issue per step in `development-strategy.md`](https://github.com/fmkarakus/app-theme/issues?q=is%3Aissue+is%3Aclosed)
- [x] [One closed PR per step in `development-strategy.md`](https://github.com/fmkarakus/app-theme/pulls?q=is%3Apr+is%3Aclosed)
- [x] A complete [README](https://github.com/fmkarakus/app-theme/blob/master/README.md)

**Comment by snicoll** [comment]
Great work @fmkarakus!
