### ISSUE TITLE
Olga Kozmovskaia: incremental development, week 2, homework

### ISSUE THREAD

**Issue by okozmovskaya** [HackYourFutureBelgium/class-9-10#219]
# Week 2

## Incremental-development

- [assignments](https://github.com/HackYourFutureBelgium/incremental-development/blob/master/week-2/README.md)

## Prep Work

- [x] Collaborating on GitHub
- [x] WireFrames
- [x] Pair Programming

---

## In Class

- [x] Isolate: [live](https://katerynakim.github.io/git-workflow-workshop-for-two/), [source](https://github.com/katerynakim/git-workflow-workshop-for-two/commits/master)
- [x] Integrate: [live](https://okozmovskaya.github.io/git-workflow-for-two-integrate/), [source](https://github.com/okozmovskaya/git-workflow-for-two-integrate)

---

### Suggested Study

- [x] Git & GitHub
- [x] Responsive Design
- [x] CLI

### Exercises:

- [x] `:emoji:` exercise 1: [repo](https://github.com/okozmovskaya/html-css-git-exercises/tree/master/week-2)
- [ ] `:emoji:` 

### Project

App-Theme

- [x] [repo](https://github.com/okozmovskaya/app-theme)
- [x] [live](https://okozmovskaya.github.io/app-theme/)
- [x] [development-strategy](https://github.com/okozmovskaya/app-theme/blob/master/development-strategy.md)
- [x] One branch per step in my `development-strategy.md`
- [x] One closed Issue per step in my `development-strategy.md`
- [x] One closed Pull Request per step in my `development-strategy.md`
- [x] A complete README

**Comment by otagi** [comment]
Good code, nice wireframes, perfect branching. Well Done!

**Comment by okozmovskaya** [comment]
Thank you, Tiago!)))
