### ISSUE TITLE
Abel: working with code, Week 1

### ISSUE THREAD

**Issue by abelRoland** [HackYourFutureBelgium/class-9-10#22]
- [X] :egg: [Group Intro Repo](https://github.com/abelRoland/bioRepo)
- [X] :egg: Started my HYF Directory
![HYF_ScreeShot](https://user-images.githubusercontent.com/60756836/81540693-4c11a100-9372-11ea-8f97-272939f0079b.jpg)
- [X] :egg: _First Week on GitHub_
![FirstWeek](https://user-images.githubusercontent.com/60756836/81541837-08b83200-9374-11ea-9d74-f1e056d34fec.png)
- [X] :egg: [My student bio](https://github.com/HackYourFutureBelgium/class-9-10/blob/master/student-bios/abelRoland.md)
- [X] :egg: [my `hack-my-future` repo](https://github.com/abelRoland/hack-my-future)
- [X] :egg: my markdown home page: [Live](https://abelroland.github.io/), [Source](https://github.com/abelRoland/abelroland.github.io)
- [X] :egg: [My _Learnables_ Project Board](https://github.com/users/abelRoland/projects/1)

**Comment by colevandersWands** [comment]
🐎
