### ISSUE TITLE
Yana: Incremental Development, Week 2, Homework

### ISSUE THREAD

**Issue by adekimpianna** [HackYourFutureBelgium/class-9-10#220]
# Week 2

## Incremental Development

- [Assignments](https://github.com/HackYourFutureBelgium/incremental-development/tree/master/week-2)

## Prep Work

- [x] Collaborating on GitHub
- [x] WireFrames
- [x] Pair Programming

---

## In Class

- [x] Isolate: I have understood the exercises
- [x] Integrate: One team with Harun and Miroslav [Live](https://harunaltunhr.github.io/integrate-week2/), [Source](https://github.com/harunaltunhr/integrate-week2)

---

### Suggested Study

- [x] Git & GitHub
- [x] Responsive Design
- [x] CLI
 
### Exercises:

- [x] 🥚 html-css-git-exercises - Week 2: [Repo](https://github.com/adekimpianna/html-css-git-exercises)
- [ ] 🐣 [HTML-CSS-Practice-Problems](https://github.com/DevMountain/HTML-CSS-Practice-Problems):  [Repo](https://github.com/your-user-name/exercise-name)
- [ ] 🐥 css-exercises

### Project

Project name: 
#### app-theme

- [x] [repo](https://github.com/adekimpianna/app-theme)
- [x] [live](https://adekimpianna.github.io/app-theme/)
- [x] [development-strategy](https://github.com/adekimpianna/app-theme/blob/master/development-strategy.md)
- [x] One branch per step in my `development-strategy.md`
- [x] One closed Issue per step in my `development-strategy.md`
- [x] One closed Pull Request per step in my `development-strategy.md`
- [x] A complete README

**Comment by snicoll** [comment]
Well done @adekimpianna! I've added a few comments in the integrate exercise you've done with Harun and Miroslav.

Great development strategy once again and a very polished README, this is excellent. A few remarks:

* `1-introduction` is not a branch (at least on GitHub) and there is no PR for it. No need to act on it  though :)
* Usually the `Closes #id` is written on a line of its own, not at the end of the description. It's not critical but it is better to separate the description from the issue reference.

Here is an exemple of a commit

```
create services page

relates #6 three packages of service , update internal links
```

You'd rather have your own title as a proper sentence (imperative style, starting with an upper case), the a description of the commit. And finally the reference to the GitHub issue, something like

```
Add services pages

This commit adds a dedicated services page describing what can be
bought from the company.

Closes #6
```

Notice that the body is wrapped on 72 characters. If you want to know more about the best practices around git commit, [this blog post](https://chris.beams.io/posts/git-commit/) is very interesting.
