### ISSUE TITLE
Fatih: working with code, Week 1

### ISSUE THREAD

**Issue by fmkarakus** [HackYourFutureBelgium/class-9-10#24]
- [x] :egg: [Group Intro Repo](https://github.com/fmkarakus/groupintro)
- [x] :egg: Started my HYF Directory
- [x] :egg: _First Week on GitHub_
- [x] :egg: [My student bio](https://github.com/fmkarakus/class-9-10/blob/master/student-bios/fmkarakus.md)
- [x] :egg: [my `hack-my-future` repo](https://github.com/fmkarakus/hack-my-future)
- [x] :egg: my markdown home page: [Live](https://fmkarakus.github.io), [Source](https://github.com/fmkarakus/fmkarakus.github.io)
- [x] :egg: [My _Learnables_ Project Board](https://github.com/users/fmkarakus/projects/1)

**Comment by colevandersWands** [comment]
🌚
