### ISSUE TITLE
Yulia Dogrusoz: working with code, Week 1

### ISSUE THREAD

**Issue by julia-sod** [HackYourFutureBelgium/class-9-10#25]
- [x] :egg: [Group Intro Repo](https://github.com/julia-sod/our-bio)
- [x] :egg: Started my HYF Directory
- [x] :egg: _First Week on GitHub_
- [x] :egg: [My student bio](https://github.com/hackyourfuturebelgium/class-9-10/tree/master/student-bios/julia-sod.md)
- [x] :egg: [my `hack-my-future` repo](https://github.com/julia-sod/hack-my-future)
- [x] :egg: my markdown home page: [Live](https://julia-sod.github.io), [Source](https://github.com/julia-sod/julia-sod.github.io)
- [x] :egg: [My _Learnables_ Project Board](https://github.com/users/julia-sod/projects/1)

**Comment by colevandersWands** [comment]
🦓
