### ISSUE TITLE
Yana: incremental development, week 2

### ISSUE THREAD

**Issue by adekimpianna** [HackYourFutureBelgium/class-9-10#250]
# Wednesday Check-In

__Incremental Development, Week 2__

## Progress

The egg exercise is done, Isolation is done and I just started doing the project. **I love making wireframes**, maybe I should google and read more about websites and app designing in my free time. Any suggestions? 

## Blocked

It is not a real block, but is that normal that the responsive design among different browsers appear differently? Or did I make a mistake? 😕   

**From Google Chrome = Chaos!!**
![AppTheme - Google Chrome](https://user-images.githubusercontent.com/62487749/83064846-c7599f00-a062-11ea-826e-47ac1feb6446.jpg)  
  
**From Mozilla = Looking good!**
![AppTheme - Mozilla Firefox](https://user-images.githubusercontent.com/62487749/83064924-e35d4080-a062-11ea-8b5f-e891b12886ff.jpg)

  

## Next Steps

* Start the group project for Integration on Thursday.  
* Complete the other homework on Friday.  
* Start the prep work and html-css-exercise of WEEK 3 on Saturday, so that next week I can have free time to start making my own mocking websites and to study **JavaScript, which is sooooo grey for me** up to now (I am not sure about it). I am sure there I will have many blocks for the coaches 💯 

## Tip(s) of the week

Still the same like last week, take time to learn and process everything, no hurry.

**Comment by snicoll** [comment]
>  is that normal that the responsive design among different browsers appear differently? Or did I make a mistake?

Yes. Browsers work differently with different features and it can be challenging sometimes to get the expect result on them. I can't help you with the specific problem unfortunately.

**Comment by adekimpianna** [comment]
okay, thanks @snicoll
