### ISSUE TITLE
HazemBittar: Incremental Development, week 2, homework

### ISSUE THREAD

**Issue by HazemBittar** [HackYourFutureBelgium/class-9-10#254]
# Week 2

## Incremental Development

- [assignments](https://github.com/hackyourfuturebelgium/incremental-development/tree/master/week-2)

## Prep Work

- [x] Collaborating on GitHub
- [x] WireFrames
- [x] Pair Programming

---

## In Class

- [x] Isolate: I have understood the exercises
- [x] Integrate: I have understood the exercises

---

### Suggested Study

- [x] Git & GitHub
- [x] Responsive Design
- [x] CLI

### Exercises:

- [x] :egg: html-css-git-exercises - Week 2 : [repo](https://github.com/HazemBittar/html-css-git-exercises/tree/master/week-2),
- [x] :hatching_chick:  HTML-CSS-Practice-Problems : [repo](https://github.com/HazemBittar/HTML-CSS-Practice-Problems/tree/master/level-2)
### Project

project name: App-theme

- [x] [repo](https://github.com/HazemBittar/app-theme-22)
- [x] [live](https://hazembittar.github.io/app-theme-22/)
- [x] [development-strategy](https://github.com/HazemBittar/app-theme-22/blob/master/development-strategy.md)
- [x] One branch per step in my `development-strategy.md`
- [x] One closed Issue per step in my `development-strategy.md`
- [x] One closed Pull Request per step in my `development-strategy.md`
- [x] A complete README

**Comment by otagi** [comment]
The code looks good, and the result works well. Nice detailed Readme file as well.

Don't hesitate to ask more questions about git if its usage is not clear enough yet.
