### ISSUE TITLE
Galal KORO: Incremental Development, Week 2 

### ISSUE THREAD

**Issue by galalkoro** [HackYourFutureBelgium/class-9-10#255]

**Comment by snicoll** [comment]
@galalkoro I am a bit confused. What is the difference between this issue and #223? You should only have on `homework` issue per week and the templates for the description has been shared on slack.

**Comment by galalkoro** [comment]
> @galalkoro I am a bit confused. What is the difference between this issue and #223? You should only have on `homework` issue per week and the templates for the description has been shared on slack.
 > @snicoll SORRY I did finished the project the I made each of one an issue but I will delete it and put in issue #223
