### ISSUE TITLE
Mari: incremental-development, week 3

### ISSUE THREAD

**Issue by Meowri** [HackYourFutureBelgium/class-9-10#301]
# Wednesday Check-In

__incremental-development, week 3__

## Progress

What have you learned and/or completed so far this week?
- I have started to understand how branching, pushing, pulling and merging works and how it plays a role in a future career as a developer.

## Blocked

What are you having trouble understanding? What parts of the homework are you struggling to complete?
- I am still behind and I need to catch up still.

## Next Steps

What are your goals and your study plans for the rest of the week?
-get as far as I can but not to get caught up in the fact that I am behind, I can rather re-visit this module later when I have time. Because I struggle with CSS, that was any-case the plan.

## Tip(s) of the week

Share some tips, tricks or links that made a big difference for you.

**Comment by colevandersWands** [comment]
> I have started to understand how branching, pushing, pulling and merging works and how it plays a role in a future career as a developer.

:+1:

**Comment by Meowri** [comment]
I feel like I understand what I should have learned out of this week, although it is still a slow process, I understand what I need to do and I get it there eventually. I will re visit this module when I have time again.
