### ISSUE TITLE
Olga Kozmovskaia: Incremental Development, week 3, homework

### ISSUE THREAD

**Issue by okozmovskaya** [HackYourFutureBelgium/class-9-10#307]
# Week N 3

## Incremental Development

- [assignments](https://github.com/HackYourFutureBelgium/incremental-development/tree/master/week-3)

## Prep Work

- [x] GitHub Code Review

---

## In Class

- [x] Isolate: [source](https://github.com/katerynakim/isolate)
- [x] Integrate: [live](https://katerynakim.github.io/Semantic-layout-groupwebpage/), [source](https://github.com/katerynakim/Semantic-layout-groupwebpage)

---

### Suggested Study

- [x] Collaboration
- [x] Web Accessibility
- [x] CLI

### Exercises:

- [x] `:emoji:` exercise 1: [repo](https://github.com/okozmovskaya/html-css-git-exercises/tree/master/week-3)
- [x] `:emoji:` HTML-CSS-Practice-Problems: [repo](https://github.com/your-user-name/exercise-name), [live](https://your-user-name.github.io/exercise-name/)
- [ ] css-exercises

### Project

`DuckDuckClone`

- [x] [repo](https://github.com/okozmovskaya/duck-duck-clone)
- [x] [live](https://okozmovskaya.github.io/duck-duck-clone/)
- [x] [development-strategy](https://github.com/user-name/project-name/tree/master/development-strategy.md)
- [x] [One branch per step in `development-strategy.md`](https://github.com/okozmovskaya/duck-duck-clone/blob/master/development-strategy.md)
- [x] [One closed Issue per step in `development-strategy.md`](https://github.com/okozmovskaya/duck-duck-clone/issues)
- [x] [One closed PR per step in `development-strategy.md`](https://github.com/okozmovskaya/duck-duck-clone/pulls)
- [x] [A project board](https://github.com/okozmovskaya/duck-duck-clone/projects) with all issues moved to "Done"
- [ ] A complete README

**Comment by otagi** [comment]
Well done @okozmovskaya and @razvanbrb!

I noticed you used sentences like "This PR connect with issue #N" in the PR descriptions. It's good, and correctly links the issue. Remember you can also save yourself some work by writing something like "Closes #N", to let GitHub auto-close the linked issue when you merge the PR. (see [GitHub's documentation](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))

Also, don't hesitate to use the issues comments to discuss the project evolution, the problems you encounter, etc. The advantage over Slack for example is that if a new member joins the team, they can read these discussions in context to get up to speed. Same for your future self, when you come back to the project after a few weeks. Not important here, but useful on larger projects.

**Comment by okozmovskaya** [comment]
Thank you, Tiago))))
We forget about "Closes #", thank you for remembering!
Unfortunately, now we we perceive a github workflow (project board, issues and comments to PR) like as the perfomance our best skills, but I understand that it's not correct and in real life, in real work we will use this tools for communication and real workflow. Thank you for your advice I will follow it.
