### ISSUE TITLE
Mamé, incremental  development week3 

### ISSUE THREAD

**Issue by mametur** [HackYourFutureBelgium/class-9-10#314]
# Sunday Review

__incremental  development week3 __

## The Problem

1. I am not clear with the validation part.

- Do we have to solve also "warning "?
- how can we solve links errors for css validation (such as bootstrap &&font awesome)?
 [my case](https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fmametur.github.io%2Fduck-duck-clone%2F)

**Comment by snicoll** [comment]
Yes you need to solve warnings. I didn't understand the second question.

**Comment by mametur** [comment]
@snicoll thank you so much. The second question is the URL which I put into the HTML head tag  give errors if you click on [here](https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fmametur.github.io%2Fduck-duck-clone%2F) you will understand better what I mean
