### ISSUE TITLE
LujiAnna: Debugging, week 1

### ISSUE THREAD

**Issue by LujiAnna** [HackYourFutureBelgium/class-9-10#361]
# Wednesday Check-In

__Debugging, week 1__

## Progress

Learned how to debug from browser dev tools

## Blocked

[Isolate](https://hackyourfuture.be/debugging/week-1/#/logical-operators-exercises): Logical Operators [Exercises](https://github.com/HackYourFutureBelgium/debugging/tree/master/isolate/logical-operators/exercises)
* I could not write any function which would evaluate PASS

## Next Steps

Goals and study plans for the rest of the week: Complete - Integrate, Assignments (exercises & study) & Project

## Tips of the week

Some tips / tricks that made a big difference for me.
>
Learned how logical operators work in the cases of AND and OR
* ||: program STOPS when encountered condition is TRUE, and proceeds if condition is false
* &&: program STOPS when encountered condition is FALSE, and proceeds if condition is true

**Comment by colevandersWands** [comment]
> I could not write any function which would evaluate PASS

Try using a condition if/else

**Comment by LujiAnna** [comment]
Thanks @colevandersWands !!
It's working already for the ternary function :-)
