### ISSUE TITLE
LujiAnna: debugging, week 2

### ISSUE THREAD

**Issue by LujiAnna** [HackYourFutureBelgium/class-9-10#397]
# Wednesday Check-In

__Debugging__, week 1&2

## Progress

Learned and/or completed so far this week: Isolate examples

## Blocked

Trouble understanding: Debugging with VSCode
Parts of the homework are you struggling to complete: 
* Isolate exercise debugging using Vscode.
* I was following [this tutorial](https://www.youtube.com/watch?v=DsH-fizHkcY)
* I have downloaded node and also extension: debugger for chrome
* Problem: I can set breakpoints, but I can not run the step-in/through icons,  sometimes the icons are not showing up on editor 

## Next Steps

Goals and your study plans for the rest of the week: Complete the Exercises & Project

## Tip(s) of the week

[Adding string to a number in javascript](https://stackoverflow.com/questions/16522648/javascript-adding-a-string-to-a-number)

**Comment by colevandersWands** [comment]
@LujiAnna if you're really struggling with the Node debugger and just want to focus on the exercises, you can always run the `index.html` in `week-x` using LiveServer.  Then you can use the browser's debugger or JS Tutor for the isolate exercises, copy-pasting the code into VSC when it's ready

There's no rush to learn the Node debugger

**Comment by LujiAnna** [comment]
Thanks @colevandersWands 🌟 
This helped me out to even do this week's project as well :)
