### ISSUE TITLE
Abdulhamid : working with code, Week 1

### ISSUE THREAD

**Issue by ali1996-sy** [HackYourFutureBelgium/class-9-10#44]
- [x] :egg: [Group Intro Repo](https://github.com/ali1996-sy/group-intro-9-10_3)
- [x] :egg: Started my HYF Directory
- [x] :egg: _First Week on GitHub_
- [x] :egg: [My student bio](https://hackyourfuture.be/class-9-10/?student=ali1996-sy)
- [x] :egg: [my `hack-my-future` repo](https://github.com/ali1996-sy/hack-my-future)
- [x] :egg: my markdown home page: [Live](https://ali1996-sy.github.io/), [Source](https://github.com/ali1996-sy/ali1996-sy.github.io)
- [x] :egg: [My _Learnables_ Project Board](https://github.com/users/ali1996-sy/projects/2)

**Comment by colevandersWands** [comment]
some picky details, then you're all set!
* can you replace the link to your student bio with this one: https://github.com/hackyourfuturebelgium/class-9-10/blob/master/student-bios/Abdulhamid_Ali.md
* and there's a table that isn't rendering on your live home page

**Comment by colevandersWands** [comment]
Hey, sorry I missed this the first time around.  could you also change the name of your home page repository from `abdulhamid.github.io` to `ali1996-sy.github.io`

You'll know you've done it right when this link opens to your home page: https://ali1996-sy.github.io/

**Comment by ali1996-sy** [comment]
thank i did it  @colevandersWands

**Comment by colevandersWands** [comment]
@ali1996-sy , I missed a detail when I reviewed your homework.  Can you rename you student-bio file to match your github user name?  This way we can find it using the links on the class home page: https://hackyourfuture.be/class-9-10/?student=ali1996-sy

**Comment by ali1996-sy** [comment]
#44 resolved
