### ISSUE TITLE
Oguz: working with code, Week 1

### ISSUE THREAD

**Issue by oguzkarademir** [HackYourFutureBelgium/class-9-10#46]
> !:warning:! Replace `your-user-name` with your actual GitHub user name and `repo-name` with the name of your class repo !:warning:!

- [x] :egg: [Group Intro Repo](https://github.com/oguzkarademir/class910-group3)
- [x] :egg: Started my HYF Directory
- [x] :egg: _First Week on GitHub_
- [x] :egg: [My student bio](https://github.com/HackYourFutureBelgium/class-9-10/blob/master/student-bios/oguzkarademir.md)
- [x] :egg: [my `hack-my-future` repo](https://github.com/oguzkarademir/hack-my-future)
- [x] :egg: my markdown home page: [Live](https://oguzkarademir.github.io/), [Source](https://github.com/oguzkarademir/oguzkarademir.github.io)
- [x] :egg: [My _Learnables_ Project Board](https://github.com/users/oguzkarademir/projects/2)

**Comment by colevandersWands** [comment]
🤗
