### ISSUE TITLE
Sharaf: WorkingWithCode, week1

### ISSUE THREAD

**Issue by sharafcs50** [HackYourFutureBelgium/class-9-10#47]
# Sunday Review

__WorkingWithCode, 1__

## The Problem
All the files in VSC appeared as "deleted", I could not work on the project anymore (I use Ubuntu).

Explain the situation:
I was working on VSC (had folder and files opened) and later changed the name of the folder (from my desktop).

## Best Efforts
I did fix the issue by opening the 'renamed' folder again in VSC and continued working from there.

**Question:**
Is this something normal or something that we should avoid and are there any other best-practices or things that we should avoid in relation to moving/renaming files/folders?

**Comment by snicoll** [comment]
I am not 100% sure of what you did exactly but if you rename a folder that is managed by Git, git considers that the files are gone as their location is part of their identity.

Let's assume you have a repository with a directory called `a` and a filed `test.txt` in it:

```
.
└── a
    └── test.txt

1 directory, 1 file
``` 

Now, let's assume you rename `a` to `b`. It doesn't matter how you do it, via the explorer, the shell or any other tool. 

Here is the output of  `git status`:

```
On branch master
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	deleted:    a/test.txt

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	b/
```

So `a/test.txt` has been deleted (indeed, the file is now in a directory called `b`), and `b` is a new location that git knows nothing about.

Does this help?

**Comment by otagi** [comment]
If you rename files or folders inside your project, then you have to tell git about your changes, like Stéphane explained.

If you rename the project folder itself, then no need to tell git. 

And yes, it's normal that your project can disappear from VSCode. Some apps can detect external file name changes, some can't. It depends if the developers programmed that detection or not.

Closing the old project in VSCode and re-opening it does the trick, like you did.

**Comment by snicoll** [comment]
@sharafcs50 can this one be closed or do you need help still?

**Comment by sharafcs50** [comment]
It can be closed
