### ISSUE TITLE
Pavel Bidenko: working with code, Week 1

### ISSUE THREAD

**Issue by pavelbidenko2018** [HackYourFutureBelgium/class-9-10#49]
- [x] :egg: [Group Intro Repo](https://github.com/pavelbidenko2018/HYF_week1)
- [x] :egg: Started my HYF Directory
- [x] :egg: _First Week on GitHub_
- [x] :egg: [My student bio](https://github.com/HackYourFutureBelgium/class-9-10/blob/master/student-bios/pavelbidenko2018.md)
- [x] :egg: [my `hack-my-future` repo](https://github.com/pavelbidenko2018/hack-my-future)
- [x] :egg: my markdown home page: [Live](https://pavelbidenko2018.github.io), [Source](https://github.com/pavelbidenko2018/pavelbidenko2018.github.io)
- [x] :egg: [My _Learnables_ Project Board](https://github.com/users/pavelbidenko2018/projects/1)

**Comment by colevandersWands** [comment]
@pavelbidenko2018 , all of the links in your issue open to `your-user-name` instead of `pavelbidenko2018`.  Can you edit the issue so the links open to the right sites?

**Comment by pavelbidenko2018** [comment]
> @pavelbidenko2018 , all of the links in your issue open to `your-user-name` instead of `pavelbidenko2018`. Can you edit the issue so the links open to the right sites?

**Comment by pavelbidenko2018** [comment]
@colevandersWands 

Thank you! Understood. Already updated,

**Comment by colevandersWands** [comment]
🏆
