### ISSUE TITLE
Yana: Working with code, Week 1

### ISSUE THREAD

**Issue by adekimpianna** [HackYourFutureBelgium/class-9-10#50]
> !:warning:! Replace `your-user-name` with your actual GitHub user name and `repo-name` with the name of your class repo !:warning:!

- [x] :egg: [Group Intro Repo](https://github.com/adekimpianna/group-biography)
- [x] :egg: Started my HYF Directory
- [x] :egg: _First Week on GitHub_
- [x] :egg: [My student bio](https://github.com/HackYourFutureBelgium/class-9-10/blob/master/student-bios/adekimpianna.md)
- [x] :egg: [my `hack-my-future` repo](https://github.com/adekimpianna/hack-my-future)
- [x] :egg: my markdown home page: [Live](https://adekimpianna.github.io/), [Source](https://github.com/adekimpianna/adekimpianna.github.io)
- [x] :egg: [My _Learnables_ Project Board](https://github.com/users/adekimpianna/projects/1)

**Comment by colevandersWands** [comment]
💯 👍 💯
