### ISSUE TITLE
Mari: Testing , week 2

### ISSUE THREAD

**Issue by Meowri** [HackYourFutureBelgium/class-9-10#501]
# Wednesday Check-In

__Testing, week 2__

## Progress

I am starting to get more familiar with Javascript, I feel like my fear of not knowing the code is really keeping me from jumping into debugging and testing like I should. 

## Blocked

I have been spending too much time doing another course, fundamentals of JavaScript, and I feel that it has given me some clarity and confidence to jump into this module. I am really hoping that the coaches forgive me, and that my approach to the whole course has become a pace, rather than a race, and I am really prioritizing not taking on to much and re-visiting places where I was stuck rather than rushing through.

## Next Steps

I will keep up my 1 hour a day min goal, I am not yet able to up my min yet.
I will jump into this module and catch up this week and last weeks homework.
I will assist my team to do the same :)

## Tip(s) of the week

You can use loops to test.
You can become a QA tester without knowing coding 
Use Math.floor to remove decimal points
Learn when to use:
Break / Continue
For loop / While loop / Do While loop

**Comment by colevandersWands** [comment]
> I have been spending too much time doing another course, fundamentals of JavaScript, and I feel that it has given me some clarity and confidence to jump into this module.

@Meowri , this is great to hear! What counts is that you've found something you're comfortable with and that you're moving forward.  The class material will always be there to review later. Get in touch if you need some help getting back to the assignments

**Comment by Meowri** [comment]
Thank you Evan, that really makes me feel better. Thank you very much :) I have been in touch with Joel to assist me with that this week in particular :)
