### ISSUE TITLE
Lisa Rosanty: Working With Code, Week 1

### ISSUE THREAD

**Issue by lisarosaa** [HackYourFutureBelgium/class-9-10#51]
> !:warning:! Replace `your-user-name` with your actual GitHub user name and `repo-name` with the name of your class repo !:warning:!

- [x] :egg: [Group Intro Repo](https://github.com/lisarosaa/LetItBe-Group)
- [x] :egg: Started my HYF Directory
- [x] :egg: _First Week on GitHub_
- [x] :egg: [My student bio](https://github.com/HackYourFutureBelgium/class-9-10/blob/master/student-bios/lisarosaa.md)
- [x] :egg: [my `hack-my-future` repo](https://github.com/lisarosaa/hack-my-future)
- [x] :egg: my markdown home page: [Live](https://lisarosaa.github.io), [Source](https://github.com/lisarosaa/lisarosaa.github.io)
- [x] :egg: [My _Learnables_ Project Board](https://github.com/users/lisarosaa/projects/1)

**Comment by colevandersWands** [comment]
nice start on your notes!
