### ISSUE TITLE
Kateryna: working with code, Week 1

### ISSUE THREAD

**Issue by katerynakim** [HackYourFutureBelgium/class-9-10#52]
> !:warning:! Replace katerynakim with your actual GitHub user name and kateryna with the name of your class repo !:warning:!

- [x] :egg: [Group Intro Repo](https://github.com/katerynakim/group-intro-)
- [x] :egg: Started my HYF Directory
- [x] :egg: _First Week on GitHub_
- [x] :egg: [My student bio](https://github.com/HackYourFutureBelgium/class-9-10/blob/master/student-bios/kateryna.md)
- [x] :egg: [my `hack-my-future` repo](https://github.com/katerynakim/hack-my-future)
- [x] :egg: my markdown home page: [Live](https://katerynakim.github.io), [Source](https://github.com//katerynakim//katerynakim.github.io)
- [x] :egg: [My _Learnables_ Project Board](https://github.com/users//katerynakim/projects/1)

**Comment by colevandersWands** [comment]
☂️

**Comment by colevandersWands** [comment]
@katerynakim , I missed a detail when I was reviewing your student bio. Right now it's only on your fork, you still need to make a pull request to the main class repo so we can find it from your "details" page: https://hackyourfuture.be/class-9-10/?student=KaterynaKim

**Comment by katerynakim** [comment]
Hello Evan,

Kindly please check if it is well done now https://github.com/katerynakim/class-9-10/pull/2.

Thank you!

**Comment by colevandersWands** [comment]
@katerynakim , still not quite.  The file should be named after your github user name like so: https://github.com/hackyourfuturebelgium/class-9-10/tree/master/student-bios/KaterynaKim.md

**Comment by katerynakim** [comment]
@colevandersWands file renamed : https://github.com/HackYourFutureBelgium/class-9-10/blob/master/student-bios/KaterynaKim.md

**Comment by colevandersWands** [comment]
🎈
