### ISSUE TITLE
Olga Kozmovskaya: working with code, Week 1

### ISSUE THREAD

**Issue by okozmovskaya** [HackYourFutureBelgium/class-9-10#54]
> !:warning:! Replace `your-user-name` with your actual GitHub user name and `repo-name` with the name of your class repo !:warning:!

- [x] :egg: [Group Intro Repo](https://github.com/okozmovskaya/group-intro)
- [x] :egg: Started my HYF Directory
- [x] :egg: _First Week on GitHub_
- [x] :egg: [My student bio](https://github.com/okozmovskaya/class-9-10/blob/master/student-bios/okozmovskaya.md)
- [x] :egg: [my `hack-my-future` repo](https://github.com/okozmovskaya/hack-my-future)
- [x] :egg: my markdown home page: [Live](https://okozmovskaya.github.io/), [Source](https://github.com/okozmovskaya/okozmovskaya.github.io)
- [x] :egg: [My _Learnables_ Project Board](https://github.com/users/okozmovskaya/projects/1)

**Comment by colevandersWands** [comment]
@okozmovskaya , a small thing.  Can you change the name of your home page repository to remove the final `-`?  

You'll know you've got it right when this link works: https://okozmovskaya.github.io/

**Comment by okozmovskaya** [comment]
Evan, thank you for your hint!
Done: https://okozmovskaya.github.io/

**Comment by colevandersWands** [comment]
💯
