### ISSUE TITLE
Mamé Azad: working with code, Week 1

### ISSUE THREAD

**Issue by mametur** [HackYourFutureBelgium/class-9-10#55]
# Prep Work
- [x]  Git & GitHub for Poets
- [x]   Homework Submission Process
- [x]   the HYF Be Precourse

# Assignments
- [x] :egg: [Group Intro Repo](https://mametur.github.io/group-intro-9-10_3/)
- [x] :egg: Started my HYF Directory
- [x] :egg: _First Week on GitHub_
- [x] :egg: [My student bio](https://github.com/mametur/class-9-10/blob/master/student-bios/mametur.md)
- [x] :egg: [my `hack-my-future` repo](https://github.com/mametur/hack-my-future)
- [x] :egg: my markdown home page: [Live](https://mametur.github.io/), [Source](https://github.com/mametur/MameAzad.github.io)
- [x] :egg: [My _Learnables_ Project Board](https://github.com/users/mametur/projects/3)

**Comment by colevandersWands** [comment]
@mametur, just one fix left on your markdown home page.  The repository should be called mametur.github.io (your user name).  You'll know this is set up correctly when you can see it at this link:
* https://mametur.github.io/

**Comment by mametur** [comment]
@colevandersWands  thanks reviewed and bug fixed :pray: :

**Comment by colevandersWands** [comment]
🌟

**Comment by colevandersWands** [comment]
@mametur , a detail I missed before. Can you rename your student bio file to match your github user name?  this way we can find it from the class home page: 
https://hackyourfuture.be/class-9-10/?student=mametur
