### ISSUE TITLE
Sayed Kazimi: working with code, Week 1

### ISSUE THREAD

**Issue by Sayed94h** [HackYourFutureBelgium/class-9-10#57]
> !:warning:! Replace `your-user-name` with your actual GitHub user name and `repo-name` with the name of your class repo !:warning:!

- [x] :egg: [Group Intro Repo](https://github.com/sayed94h/Group-Intro-LetItBe)
- [x] :egg: Started my HYF Directory
- [x] :egg: _First Week on GitHub_
- [x] :egg: [My student bio](https://github.com/HackYourFutureBelgium/class-9-10/blob/master/student-bios/Sayed94h.md)
- [x] :egg: [my `hack-my-future` repo](https://github.com/sayed94h/hack-my-future)
- [x] :egg: my markdown home page: [Live](https://sayed94h.github.io), [Source](https://github.com/sayed94h/sayed94h.github.io)
- [x] :egg: [My _Learnables_ Project Board](https://github.com/Sayed94h/Project-Board/projects/1)

**Comment by colevandersWands** [comment]
@Sayed94h , can you fix the links in your issue? They all still open to `your-user-name`

**Comment by Sayed94h** [comment]
@colevandersWands  would you like to show me which links should I fix?

**Comment by colevandersWands** [comment]
if you click on the three dots in the upper-right of this issue's description you'll see the markdown source. In there you'll see a lot of `your-user-name`s.

Replacing those with your actual user name will correct the links so they open to your projects instead of 404 pages

**Comment by Sayed94h** [comment]
Thank you. I edited it.

**Comment by colevandersWands** [comment]
@Sayed94h All good! 📦

**Comment by colevandersWands** [comment]
@Sayed94h , I missed something when I reviewed your assignment before.  Can you rename your student bio file to match your github user name?  this way we can find it from the button in your "details" page: https://hackyourfuture.be/class-9-10/?student=Sayed94h

**Comment by Sayed94h** [comment]
@colevandersWands I just edited that, I tested it and I think it would be ok now.
