### ISSUE TITLE
feruz teame: working with code, Week 1

### ISSUE THREAD

**Issue by Feruzteame** [HackYourFutureBelgium/class-9-10#59]
- [x] :egg: [Group Intro Repo](https://github.com/Feruzteame/class-9-10-) 
- [x] :egg: Started my HYF Directory
- [x] :egg: _First Week on GitHub_
- [x] :egg: [My student bio](https://github.com/Feruzteame/class-9-10/blob/master/student-bios/Feruzteame.md)
- [x] :egg: [my `hack-my-future` repo](https://github.com/Feruzteame/hack-my-future)
- [x] :egg: my markdown home page: [Live](https://feruzteame.github.io/), [Source](https://github.com/Feruzteame/feruz-bios)
- [x] :egg: [My _Learnables_ Project Board](https://github.com/users/Feruzteame/projects/1)

**Comment by Feruzteame** [comment]
hi Evan this my new issue i try to work my markdown home page (i used repo name like my user name) but not source.

**Comment by colevandersWands** [comment]
One last little thing, can you change the name of your student bio file so it matches your github user name?  This way it shows up when you follow the link in your "details" page: https://hackyourfuture.be/class-9-10/?student=FeruzTeame

**Comment by Feruzteame** [comment]
@colevandersWands that means i have to create new repo with the name of my username?

**Comment by colevandersWands** [comment]
it just means you need to change the name of your bio file in this repository.  you'll know you've done it correctly when this link works: https://github.com/HackYourFutureBelgium/class-9-10/blob/master/student-bios/Feruzteame.md

**Comment by Feruzteame** [comment]
i think i done it. can you check pls.
https://github.com/Feruzteame/class-9-10/blob/master/student-bios/Feruzteame.md
