### ISSUE TITLE
Aleksandra: working with code; week 1

### ISSUE THREAD

**Issue by aleks2407** [HackYourFutureBelgium/class-9-10#6]
**Prep Work**
Materials to read, review, and practice before coming into class/

- [x] Watch at least the first 3 videos of Git & GitHub for Poets. This is an outstanding video series that will help you understand why you need Git & GitHub, with no code!
- [x] Familiarize yourself with the Homework Submission Process here at HYF.
- [x] Review the HYF Be Precourse, come ready with any questions!

**There are 7 assignments this week:**

- [x] 🥚 [Group Intro Repo](https://github.com/aleks2407/HYF-Group3-Intro)
- [x] 🥚 Start an HYF Directory
- [x] 🥚 Complete First Week on GitHub
- [x] 🥚 [My "student-bio"](https://github.com/HackYourFutureBelgium/class-9-10/blob/master/student-bios/aleks2407.md)
- [x] 🥚 [My hack-my-future Repo](https://github.com/aleks2407/hack-my-future)
- [x] 🥚 My Markdown Home Page: [Live](https://aleks2407.github.io/) ; [Source](https://github.com/aleks2407/aleks2407.github.io)
- [x] 🥚 [My Learnables Project Board](https://github.com/aleks2407/hack-my-future/projects)

**Comment by colevandersWands** [comment]
@aleks2407 , can you add links to each of your assignments?  Like in this template:
* https://github.com/HackYourFutureBelgium/class-9-10/blob/master/.github/ISSUE_TEMPLATE/my-first-homework.md

**Comment by aleks2407** [comment]
@colevandersWands  Done!

**Comment by colevandersWands** [comment]
🧡
