### ISSUE TITLE
Miroslav: working with code, Week 1

### ISSUE THREAD

**Issue by miroslavveljanoski** [HackYourFutureBelgium/class-9-10#79]
### Homework assignments, working with code, week 1 

- [x] :egg: [Group Intro Repo](https://github.com/miroslavveljanoski/group-intro-repo-9-10-5)
- [x] :egg: Started my HYF Directory
- [x] :egg: _First Week on GitHub_
- [x] :egg: [My student bio](https://github.com/HackYourFutureBelgium/class-9-10/blob/master/student-bios/miroslavveljanoski.md)
- [x] :egg: [my `hack-my-future` repo](https://github.com/miroslavveljanoski/hack-my-future)
- [x] :egg: my markdown home page: [Live](https://miroslavveljanoski.github.io/), [Source](https://github.com/miroslavveljanoski/Markdown-Home-Page)
- [x] :egg: [My _Learnables_ Project Board](https://github.com/users/miroslavveljanoski/projects/1)

**Comment by colevandersWands** [comment]
@miroslavveljanoski , what do you need help with?

**Comment by miroslavveljanoski** [comment]
Hi Even, I'm ok. I'm just finishing with the assignments and will move my issue to "ready for review" in an hour. Sorry but I'm a little slow, especially at the beginning :smile:

**Comment by colevandersWands** [comment]
You're not slow at all!  there are just more students with previous experience than normal, don't compare yourself to them

I just saw you were in "BLOCKED" so I thought I'd check in.  HazemBittar had moved your issue but thought you might have been studying together

**Comment by colevandersWands** [comment]
Nice work on all your assignments, keep this up and you'll be just fine.   The main focus in class over the next three Sundays will be Git & GitHub so there will be plenty of chance to practice and ask questions

**Comment by colevandersWands** [comment]
@miroslavveljanoski , a small thing I missed the first time around.  Can you rename your student-bio file to match your github user name? this way we can get to it from the class home page: https://hackyourfuture.be/class-9-10/?student=miroslavveljanoski
