### ISSUE TITLE
Mame Azad: working-with-code, week 1

### ISSUE THREAD

**Issue by mametur** [HackYourFutureBelgium/class-9-10#81]
# Wednesday Check-In

__working-with-code, week 1__

## Progress

What have you learned and/or completed so far this week?
- I have been learning  Markdown using efficiently and add template for awesome view.  
- Create a table in markdown is really annoying .I used this website [table generator](https://www.tablesgenerator.com/markdown_tables#)
- Learnt basic Gitkrakent work-flow

## Blocked
:see_no_evil: 

## Next Steps

What are your goals and your study plans for the rest of the week?

- if one of my classmate need a help then recap with them all steps.
- Try to learn create a Navbar in markdown.
- solve a few Freecodecamp javascript test.
- Start ubuntu tutorial

## Tip(s) of the week

Share some tips, tricks or links that made a big difference for you.
- upload picture to issue (awesome way)
- table generator for Markdown
- Use template for live github page
- [table generator](https://www.tablesgenerator.com/markdown_tables#)
- this is my Git workshop you will find some useful commands [Git_Workshop](https://github.com/mametur/GitWorkShop)
- [to show emoji with jekyll themes](https://github.com/jekyll/jemoji)

**Comment by colevandersWands** [comment]
🙈 🙉 🙊

**Comment by colevandersWands** [comment]
https://github.com/mametur/GitWorkShop 💛
