### ISSUE TITLE
Yana: working with code, week 1

### ISSUE THREAD

**Issue by adekimpianna** [HackYourFutureBelgium/class-9-10#88]
# Wednesday Check-In

__Working with Code, Week 1__

## Progress

* Making 2 repos (group and mine, both with VScode)
* Forking and staring repos that I need and like
* Cloning repos and pushing changes from VSCode via GitKraken... _so useful_ 😄 
* Contributing on the first project of student bios, by adding a new file, did pull request and merged it
* Some tutorials from learning lab GitHub training
* The rest of this week assignments 

## Blocked
* **Table was not well rendered on Live** : I have followed markdown syntax for tables from different sources, It worked good on our forgiving VScode, also on github code, but not on Live. Finally **got fixed** by asking friends on the group! Thanks @harunaltunhr  👍 
* Try to help a friend with **some picture problem which did not appear on Github preview** (not via VScode, coding done directly on Github). We observed other people's code and did some changes but still did not work on that night. But, the day after, it worked?! **solved**, but why?? 😕 

## Next Steps
Still want to do some other tutorials from learning lab Github

## What are your goals and your study plans for the rest of the week?
Start to read next week materials, I think! 

## Tip(s) of the week
1. Google a lot if stuck
2. Observe other people's code to make sure you code rightly
3. Dont be shy to ask help!
4. Work it on together with friends and help if possible 🥇 
5. Coffee and warme kersenpitjes to make you feel good sitting on your desk 🤣

**Comment by colevandersWands** [comment]
@adekimpianna , sometimes github pages just takes a while to update with your newest changes.  

And what wonderful tips! They deserve to be shared on slack

**Comment by adekimpianna** [comment]
Oh, alright! Thanks for believing on my tips, lol 🤣 <br><br> And by the way, when we want to see our md pages on the Live format, is it normal that only the readme.md page that can be seen on Live format?  <br><br> Take an example of [my group repo](https://adekimpianna.github.io/group-biography/). It is fine on Live ![image](https://user-images.githubusercontent.com/62487749/81862910-b4c36e00-956a-11ea-8356-9a9ed5bcf1ad.png). <br><br> But if I something linked to another page, for example **yana.md**  or other links here, then it turned back to the Source (it did not stay on Live). ![image](https://user-images.githubusercontent.com/62487749/81862966-c9a00180-956a-11ea-9b7a-4ce3ca35009b.png). <br> Because the one from [example repo](https://hackyourfuture.be/group-intro-example/) containing coaches bio, all linked pages stay on the Live format for example if I click Abel's. So, did I do something wrong with mine?

**Comment by colevandersWands** [comment]
the live site is working: https://adekimpianna.github.io/group-biography/Harun

But the links don't go where you expect because you used absolute paths (URLs) instead of relative paths
* `* [Harun](https://github.com/adekimpianna/MyFirstRepository/blob/master/Harun.md)`
* instead of `* [Harun](./Harun.md)`

**Comment by adekimpianna** [comment]
I have changed it and now it works! Thanks @colevandersWands
